<script setup>
  import ElIcon from '@/components/icon/icon.vue';
</script>

<template>
  <preview-group class="qa-icon-sizes">
    <preview
      name="xxx-small"
      span="6"
    >
      <ElIcon
        name="IconWorkstation16"
        color="brand-primary"
        size="xxx-small"
      />
    </preview>
    <preview
      name="xx-small"
      span="6"
    >
      <ElIcon
        name="IconWorkstation32"
        color="brand-primary"
        size="xx-small"
      />
    </preview>
    <preview
      name="x-small"
      span="6"
    >
      <ElIcon
        name="IconWorkstation32"
        color="brand-primary"
        size="x-small"
      />
    </preview>
  </preview-group>
  <preview-group class="qa-icon-sizes">
    <preview
      name="small"
      span="6"
    >
      <ElIcon
        name="IconWorkstation16"
        color="brand-primary"
        size="small"
      />
    </preview>
    <preview
      name="medium"
      span="6"
    >
      <ElIcon
        name="IconWorkstation32"
        color="brand-primary"
        size="medium"
      />
    </preview>
    <preview
      name="large"
      span="6"
    >
      <ElIcon
        name="IconWorkstation32"
        color="brand-primary"
        size="large"
      />
    </preview>
  </preview-group>
  <preview-group class="qa-icon-sizes">
    <preview
      name="x-large"
      span="6"
    >
      <ElIcon
        name="IconWorkstation16"
        color="brand-primary"
        size="x-large"
      />
    </preview>
    <preview
      name="xx-large"
      span="6"
    >
      <ElIcon
        name="IconWorkstation32"
        color="brand-primary"
        size="xx-large"
      />
    </preview>
    <preview
      name="xxx-large"
      span="6"
    >
      <ElIcon
        name="IconWorkstation32"
        color="brand-primary"
        size="xxx-large"
      />
    </preview>
  </preview-group>
</template>
