export { default as IconDrStorage16 } from './dr/IconDrStorage16.vue';
export { default as IconDrInAzure16 } from './dr/IconDrInAzure16.vue';
export { default as IconDr16 } from './dr/IconDr16.vue';
export { default as IconDrBase16 } from './dr/IconDrBase16.vue';
export { default as IconDrStorage24 } from './dr/IconDrStorage24.vue';
export { default as IconDr24 } from './dr/IconDr24.vue';
export { default as IconDrInAzure24 } from './dr/IconDrInAzure24.vue';
export { default as IconDrBase24 } from './dr/IconDrBase24.vue';
export { default as IconDrAbO32 } from './dr/IconDrAbO32.vue';
