// The Tailwind v4 `@theme inline` bridge, generated as `css/tailwind-theme.css`.
//
// This is the single source for the shadcn-compatible color names ui-react's
// components use (`bg-primary`, `text-foreground`, `border-border`, …). It used
// to be hand-maintained in `packages/ui-react/src/styles/index.css`; now the
// generator owns it. `@theme inline` emits `var(--ui-*)` references (not copied
// values), so brand (`[data-brand]`) and theme (`[data-theme]`) overrides resolve
// at paint with no rebuild. ui-react `@import`s this after the token css.

import {
  type StyleModel,
  type WriteFile,
} from '../hooks/formats/css-light-dark';
import { tailwindThemeCssFile } from '../platforms';

/** Tailwind color name → the `--ui-*` semantic token it aliases. */
const BRIDGE: Record<string, string> = {
  background: 'ui-background-surface-primary',
  foreground: 'ui-text-on-surface-primary',
  primary: 'ui-background-brand-primary',
  'primary-foreground': 'ui-glyph-on-brand-primary',
  secondary: 'ui-background-brand-secondary',
  'secondary-foreground': 'ui-glyph-on-brand-secondary',
  destructive: 'ui-background-status-danger',
  'destructive-foreground': 'ui-glyph-on-status-danger',
  muted: 'ui-background-surface-secondary',
  'muted-foreground': 'ui-text-on-surface-secondary',
  accent: 'ui-background-surface-hover',
  'accent-foreground': 'ui-text-on-surface-primary',
  border: 'ui-border-on-surface-border',
  input: 'ui-border-on-surface-border',
  ring: 'ui-border-on-surface-border-active',
};

/** Every `--ui-*` name defined anywhere in the model (primitives + all brands). */
const definedVarNames = (model: StyleModel): Set<string> => {
  const names = new Set<string>(model.primitives.vars.keys());
  for (const { base, overrides } of model.slices) {
    for (const name of base.vars.keys()) names.add(name);
    for (const o of overrides)
      for (const name of o.vars.keys()) names.add(name);
  }
  return names;
};

export function emitTailwindTheme(model: StyleModel, write: WriteFile): void {
  const defined = definedVarNames(model);
  const lines = Object.entries(BRIDGE).map(([name, target]) => {
    if (!defined.has(target)) {
      // A drifted bridge target (renamed/removed semantic token) is a real
      // problem — warn loudly but still emit, so the break is visible in review.
      console.warn(
        `tailwind-theme: bridge target --${target} (→ --color-${name}) is not a generated token`
      );
    }
    return `  --color-${name}: var(--${target});`;
  });

  write(
    tailwindThemeCssFile(),
    `/* Generated by @constructor-lab/style-dictionary — DO NOT EDIT. */\n` +
      `/* Tailwind v4 @theme inline bridge: shadcn-compatible color names →\n` +
      `   --ui-* semantic tokens. \`inline\` emits var() refs, so brand/theme\n` +
      `   overrides resolve at paint. @import after the token css. */\n\n` +
      `@theme inline {\n${lines.join('\n')}\n}\n`
  );
}
