// The Tailwind v4 `@theme inline` bridge, generated as `css/tailwind-theme.css`.
//
// This is the single source for the shadcn-compatible color names ui-react's
// components use (`bg-primary`, `text-foreground`, `border-border`, …). It used
// to be hand-maintained in `packages/ui-react/src/styles/index.css`; now the
// generator owns it. `@theme inline` emits `var(--ui-*)` references (not copied
// values), so brand (`[data-brand]`) and theme (`[data-theme]`) overrides resolve
// at paint with no rebuild. ui-react `@import`s this after the token css.

import {
  type StyleModel,
  type WriteFile,
} from '../hooks/formats/css-light-dark';
import { tailwindThemeCssFile } from '../platforms';

/** Tailwind color name → the `--ui-*` semantic token it aliases. */
const BRIDGE: Record<string, string> = {
  background: 'ui-background-surface-primary',
  foreground: 'ui-text-on-surface-primary',
  primary: 'ui-background-brand-primary',
  'primary-foreground': 'ui-glyph-on-brand-primary',
  secondary: 'ui-background-brand-secondary',
  'secondary-foreground': 'ui-glyph-on-brand-secondary',
  destructive: 'ui-background-status-danger',
  'destructive-foreground': 'ui-glyph-on-status-danger',
  muted: 'ui-background-surface-secondary',
  'muted-foreground': 'ui-text-on-surface-secondary',
  accent: 'ui-background-surface-hover',
  'accent-foreground': 'ui-text-on-surface-primary',
  border: 'ui-border-on-surface-border',
  input: 'ui-border-on-surface-border',
  ring: 'ui-border-on-surface-border-active',
};

/**
 * Tailwind elevation name → the `palette.shadow.<size>` group behind it.
 *
 * The design has three elevations, each a Figma effect style (`shadow-sm` /
 * `-md` / `-lg`) whose offset / blur / spread / color are real variables.
 * Bridging Tailwind's own `--shadow-*` namespace means the utilities already in
 * the kit render the DESIGN shadow — no component edits, and a brand or theme
 * re-pointing a shadow token is honored at paint. `shadow-md` was Tailwind's
 * default `0 4px 6px -1px`, a much tighter shadow than the design's `0 16px 32px`.
 *
 * **`sm` is deliberately NOT bridged.** All three design elevations are surface
 * shadows: `sm` is `0 8px 16px` at 30% alpha. The kit's only `shadow-sm` users
 * are the auth-layout card and the Slider's 16px thumb, and a 16px-blur 30%-alpha
 * shadow under a 16px thumb renders as a grey smudge — the design does not put a
 * surface elevation on a control that small. Until the design names a
 * control-level elevation, `shadow-xs`/`shadow-sm` stay on Tailwind's defaults,
 * which is what those two call sites were built against.
 */
const SHADOW_SIZES = ['md', 'lg'] as const;

/**
 * The four geometry parts + the color, in CSS `box-shadow` order. The color slot
 * keeps Tailwind's `--tw-shadow-color` indirection with the token as the
 * fallback, exactly as Tailwind's own defaults do — otherwise a `shadow-<color>`
 * utility would silently stop overriding the shadow's color.
 */
const shadowValue = (size: string): string =>
  `var(--ui-palette-shadow-${size}-positionx) ` +
  `var(--ui-palette-shadow-${size}-positiony) ` +
  `var(--ui-palette-shadow-${size}-blur) ` +
  `var(--ui-palette-shadow-${size}-spread) ` +
  `var(--tw-shadow-color, var(--ui-palette-shadow-${size}-color))`;

/** Every `--ui-*` name defined anywhere in the model (primitives + all brands). */
const definedVarNames = (model: StyleModel): Set<string> => {
  const names = new Set<string>(model.primitives.vars.keys());
  for (const { base, overrides } of model.slices) {
    for (const name of base.vars.keys()) names.add(name);
    for (const o of overrides)
      for (const name of o.vars.keys()) names.add(name);
  }
  return names;
};

export function emitTailwindTheme(model: StyleModel, write: WriteFile): void {
  const defined = definedVarNames(model);
  const lines = Object.entries(BRIDGE).map(([name, target]) => {
    if (!defined.has(target)) {
      // A drifted bridge target (renamed/removed semantic token) is a real
      // problem — warn loudly but still emit, so the break is visible in review.
      console.warn(
        `tailwind-theme: bridge target --${target} (→ --color-${name}) is not a generated token`
      );
    }
    return `  --color-${name}: var(--${target});`;
  });

  // `--shadow-*` is a second Tailwind namespace, so it is emitted alongside the
  // colors rather than through the `--color-*` map above.
  const shadowLines = SHADOW_SIZES.map((size) => {
    for (const part of ['positionx', 'positiony', 'blur', 'spread', 'color']) {
      const target = `ui-palette-shadow-${size}-${part}`;
      if (!defined.has(target)) {
        console.warn(
          `tailwind-theme: shadow target --${target} (→ --shadow-${size}) is not a generated token`
        );
      }
    }
    return `  --shadow-${size}: ${shadowValue(size)};`;
  });

  write(
    tailwindThemeCssFile(),
    `/* Generated by @constructor-lab/style-dictionary — DO NOT EDIT. */\n` +
      `/* Tailwind v4 @theme inline bridge: shadcn-compatible color names →\n` +
      `   --ui-* semantic tokens, plus the three design elevations onto\n` +
      `   Tailwind's --shadow-* namespace. \`inline\` emits var() refs, so\n` +
      `   brand/theme overrides resolve at paint. @import after the token css. */\n\n` +
      `@theme inline {\n${lines.join('\n')}\n\n${shadowLines.join('\n')}\n}\n`
  );
}
