// CSS rendering for the token build. Two kinds of declaration share a file:
//   - colors + dimensions + gradients → custom properties in `:root, :host` (so
//     the tokens resolve in the light DOM and inside web-component shadow roots).
//     Colors are
//     theme-aware: the light value is zipped with the matching dark value
//     (supplied via `darkTokens`, keyed by token path) into `light-dark()`.
//   - typography composites → utility classes (`.ui-typography-* { … }`). The
//     `typography/css-class` transform has already built each declaration block;
//     rendering only wraps it in the selector and indents it.
//
// `collectDecls` turns a resolved token slice into name→value / selector→block
// maps; `serializeCss` renders a file from those maps. Keeping the two apart lets
// the token builder partition tokens per output file and diff one brand against
// another (override-only files) before serializing. See context/output.md.

import type { TransformedToken } from 'style-dictionary/types';

export const CSS_LIGHT_DARK = 'css/light-dark';

/** Resolved declarations of one token slice, keyed for rendering and diffing. */
export interface Decls {
  /** CSS var name → value (colors as the `light-dark(...)` pair). */
  vars: Map<string, string>;
  /** Class selector → declaration block (typography utilities). */
  classes: Map<string, string>;
  /** Tokens that could not be represented, for the build log. */
  skipped: string[];
}

/**
 * Collect a resolved token slice into declaration maps. `darkTokens` maps a
 * token path (`a.b.c`) to its resolved dark-mode color value; a color with no
 * dark entry falls back to its light value.
 */
export function collectDecls(
  tokens: TransformedToken[],
  darkTokens: Map<string, string>
): Decls {
  const vars = new Map<string, string>();
  const classes = new Map<string, string>();
  const skipped: string[] = [];

  for (const token of tokens) {
    if (token.$type === 'color') {
      const light = typeof token.$value === 'string' ? token.$value : null;
      const dark = darkTokens.get(token.path.join('.')) ?? light;
      if (light === null || dark == null) {
        skipped.push(`${token.name} (color)`);
        continue;
      }
      vars.set(token.name, `light-dark(${light}, ${dark})`);
    } else if (token.$type === 'typography') {
      // `typography/css-class` transformed the composite into a declaration block.
      if (typeof token.$value === 'string' && token.$value.length) {
        classes.set(`.${token.name}`, token.$value);
      } else {
        skipped.push(`${token.name} (typography)`);
      }
    } else if (typeof token.$value === 'string') {
      // dimension / scalar / gradient — already CSS-ready (theme-invariant).
      vars.set(token.name, token.$value);
    } else {
      skipped.push(`${token.name} (${token.$type})`);
    }
  }

  return { vars, classes, skipped };
}

const indent = (block: string): string =>
  block
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n');

export interface SerializeOptions {
  brand: string;
  /** `semantic` or a component name — recorded in the file header. */
  tier: string;
  /** Override-only files are bare `:root, :host {}`; base files carry the theme shell. */
  isOverride: boolean;
  vars: Map<string, string>;
  classes: Map<string, string>;
}

/** Render a CSS file from declaration maps. */
export function serializeCss({
  brand,
  tier,
  isOverride,
  vars,
  classes,
}: SerializeOptions): string {
  const varLines = [...vars.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, value]) => `  --${name}: ${value};`)
    .join('\n');

  const classBlocks = [...classes.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([selector, block]) => `${selector} {\n${indent(block)}\n}`)
    .join('\n\n');

  const header =
    `/* Generated by @spec-lab/style-dictionary — DO NOT EDIT. */\n` +
    `/* Source: @spec-lab/design-tokens • brand: ${brand} • tier: ${tier}` +
    `${isOverride ? ' • overrides only' : ''} */\n`;

  // Base files declare the light/dark shell; override files only restate the
  // changed custom properties (they layer on top of the imported base).
  const root = isOverride
    ? `:root, :host {\n${varLines}\n}`
    : `:root, :host {\n  color-scheme: light dark;\n\n${varLines}\n}\n\n` +
      `[data-theme='light'], :host([data-theme='light']) {\n  color-scheme: light;\n}\n\n` +
      `[data-theme='dark'], :host([data-theme='dark']) {\n  color-scheme: dark;\n}`;

  return `${header}\n${[root, classBlocks].filter(Boolean).join('\n\n')}\n`;
}
