// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: Breadcrumb
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "textColor": {
        "breadcrumb-link-label-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "breadcrumb-link-label-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "breadcrumb-link-label-idle": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "breadcrumb-page-label": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "fill": {
        "breadcrumb-separator-icon": "light-dark(rgb(201 204 207), rgb(73 76 80))"
      },
      "fontFamily": {
        "breadcrumb-link-label-text-style": "Inter, system-ui, sans-serif",
        "breadcrumb-page-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "breadcrumb-link-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "breadcrumb-page-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "breadcrumb-separator-icon-size": "16px",
        "breadcrumb-list-gap": "4px"
      }
    },
  },
};
