// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: ButtonMenu
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-menu-dropdown-container": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "button-menu-dropdown-item-container-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-menu-dropdown-item-container-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "button-menu-dropdown-item-container-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "button-menu-primary-container-active": "light-dark(rgb(13 77 165), rgb(101 106 122))",
        "button-menu-primary-container-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-menu-primary-container-hover": "light-dark(rgb(19 84 174), rgb(23 99 207))",
        "button-menu-primary-container-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-menu-secondary-container-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-menu-secondary-container-disabled": "light-dark(transparent, transparent)",
        "button-menu-secondary-container-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "button-menu-secondary-container-idle": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "button-menu-dropdown-extras-shortcut-label": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "button-menu-dropdown-item-label": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-menu-primary-label": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-menu-secondary-label-active": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-menu-secondary-label-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-menu-secondary-label-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-menu-secondary-label-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))"
      },
      "borderColor": {
        "button-menu-dropdown-container-border-color": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-menu-dropdown-section-container-border-color": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-menu-secondary-container-border-color-active": "light-dark(transparent, transparent)",
        "button-menu-secondary-container-border-color-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-menu-secondary-container-border-color-hover": "light-dark(transparent, transparent)",
        "button-menu-secondary-container-border-color-idle": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fill": {
        "button-menu-dropdown-extras-cascade-icon": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-menu-dropdown-item-icon": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-menu-primary-icon": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-menu-secondary-icon-active": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-menu-secondary-icon-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-menu-secondary-icon-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-menu-secondary-icon-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))"
      },
      "fontFamily": {
        "button-menu-dropdown-extras-shortcut-label-text-style": "Inter, system-ui, sans-serif",
        "button-menu-dropdown-item-label-text-style": "Inter, system-ui, sans-serif",
        "button-menu-global-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "button-menu-dropdown-extras-shortcut-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "button-menu-dropdown-item-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "button-menu-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "button-menu-dropdown-container-border-width": "1px",
        "button-menu-dropdown-container-gap": "0px",
        "button-menu-dropdown-container-padding-x": "0px",
        "button-menu-dropdown-container-padding-y": "0px",
        "button-menu-dropdown-item-container-gap": "8px",
        "button-menu-dropdown-item-container-height": "40px",
        "button-menu-dropdown-item-container-padding-x": "12px",
        "button-menu-dropdown-item-container-padding-y": "8px",
        "button-menu-dropdown-section-container-border-width": "1px",
        "button-menu-dropdown-section-container-padding-x": "0px",
        "button-menu-dropdown-section-container-padding-y": "0px",
        "button-menu-dropdown-section-list-gap": "0px",
        "button-menu-global-container-gap": "8px",
        "button-menu-global-container-height": "32px",
        "button-menu-global-container-padding-x": "12px",
        "button-menu-global-container-padding-y": "8px",
        "button-menu-global-container-width-min": "64px",
        "button-menu-global-icon-size": "16px",
        "button-menu-secondary-container-border-width": "1px"
      },
      "borderRadius": {
        "button-menu-dropdown-container-border-radius": "4px",
        "button-menu-global-container-border-radius": "4px"
      }
    },
  },
};
