// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: Button
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-destructive-container-active": "light-dark(rgb(173 31 31), rgb(248 195 195))",
        "button-destructive-container-disabled": "light-dark(rgb(253 237 237), rgb(87 15 15))",
        "button-destructive-container-hover": "light-dark(rgb(195 34 34), rgb(244 154 154))",
        "button-destructive-container-idle": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "button-inverted-container-active": "light-dark(rgb(19 84 174), rgb(23 99 207))",
        "button-inverted-container-disabled": "light-dark(rgb(6 54 121), rgb(190 215 244))",
        "button-inverted-container-hover": "light-dark(rgb(13 77 165), rgb(101 106 122))",
        "button-inverted-container-idle": "light-dark(rgb(11 66 142), rgb(113 119 134))",
        "button-primary-container-active": "light-dark(rgb(13 77 165), rgb(101 106 122))",
        "button-primary-container-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-primary-container-hover": "light-dark(rgb(19 84 174), rgb(23 99 207))",
        "button-primary-container-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-secondary-container-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-secondary-container-disabled": "light-dark(transparent, transparent)",
        "button-secondary-container-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "button-secondary-container-idle": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "button-ai-label-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-label-disabled": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-label-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-label-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-label-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-label-disabled": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-label-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-label-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ghost-label-active": "light-dark(rgb(6 54 121), rgb(190 215 244))",
        "button-ghost-label-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-ghost-label-hover": "light-dark(rgb(19 84 174), rgb(23 99 207))",
        "button-ghost-label-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-inverted-label-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-inverted-label-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(255 255 255 / 0.6))",
        "button-inverted-label-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-inverted-label-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-label-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-label-disabled": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-label-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-label-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-secondary-label-active": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-secondary-label-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-secondary-label-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-secondary-label-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))"
      },
      "borderColor": {
        "button-inverted-container-border-color-active": "light-dark(transparent, transparent)",
        "button-inverted-container-border-color-disabled": "light-dark(rgb(255 255 255 / 0.102), rgb(255 255 255 / 0.102))",
        "button-inverted-container-border-color-hover": "light-dark(transparent, transparent)",
        "button-inverted-container-border-color-idle": "light-dark(transparent, transparent)",
        "button-secondary-container-border-color-active": "light-dark(transparent, transparent)",
        "button-secondary-container-border-color-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-secondary-container-border-color-hover": "light-dark(transparent, transparent)",
        "button-secondary-container-border-color-idle": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fill": {
        "button-ai-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-icon-disabled": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ai-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-icon-disabled": "light-dark(rgb(255 255 255 / 0.102), rgb(255 255 255 / 0.102))",
        "button-destructive-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-destructive-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-ghost-icon-active": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-ghost-icon-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-ghost-icon-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-ghost-icon-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-inverted-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-inverted-icon-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(255 255 255 / 0.6))",
        "button-inverted-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-inverted-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-icon-disabled": "light-dark(rgb(255 255 255 / 0.102), rgb(255 255 255 / 0.102))",
        "button-primary-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-primary-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "button-secondary-icon-active": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-secondary-icon-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "button-secondary-icon-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "button-secondary-icon-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))"
      },
      "fontFamily": {
        "button-global-label-text-style": "Inter, system-ui, sans-serif",
        "button-ghost-label-text-style-active": "Inter, system-ui, sans-serif",
        "button-ghost-label-text-style-disabled": "Inter, system-ui, sans-serif",
        "button-ghost-label-text-style-hover": "Inter, system-ui, sans-serif",
        "button-ghost-label-text-style-idle": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "button-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "button-ghost-label-text-style-active": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "button-ghost-label-text-style-disabled": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "button-ghost-label-text-style-hover": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "button-ghost-label-text-style-idle": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "button-global-container-gap": "8px",
        "button-global-container-height": "32px",
        "button-global-container-padding-y": "8px",
        "button-global-icon-size": "16px",
        "button-ai-container-padding-x": "12px",
        "button-ai-container-width-min": "64px",
        "button-destructive-container-padding-x": "12px",
        "button-destructive-container-width-min": "64px",
        "button-ghost-container-padding-x": "0px",
        "button-inverted-container-border-width": "1px",
        "button-inverted-container-padding-x": "12px",
        "button-inverted-container-width-min": "64px",
        "button-primary-container-padding-x": "12px",
        "button-primary-container-width-min": "64px",
        "button-secondary-container-border-width": "1px",
        "button-secondary-container-padding-x": "12px",
        "button-secondary-container-width-min": "64px"
      },
      "borderRadius": {
        "button-global-container-border-radius": "4px"
      }
    },
  },
};
