// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: Chips
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "chips-container-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "chips-container-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "chips-container-idle": "light-dark(rgb(248 250 252), rgb(24 25 27))"
      },
      "textColor": {
        "chips-label": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "chips-border-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "chips-border-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "chips-border-idle": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fill": {
        "chips-icon": "light-dark(rgb(23 99 207), rgb(71 152 245))"
      },
      "fontFamily": {
        "chips-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "chips-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "chips-border-width": "1px",
        "chips-container-gap": "4px",
        "chips-container-height": "24px",
        "chips-container-padding-x": "8px",
        "chips-container-width-min": "48px",
        "chips-icon-size": "16px"
      },
      "borderRadius": {
        "chips-border-radius": "12px"
      }
    },
  },
};
