// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: InputDatePicker
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "input-date-picker-global-box-disabled": "light-dark(rgb(248 250 252), rgb(24 25 27))",
        "input-date-picker-global-box-hover": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "input-date-picker-global-box-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "input-date-picker-global-label-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-date-picker-global-label-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-date-picker-global-label-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-date-picker-global-placeholder-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-date-picker-global-placeholder-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "input-date-picker-global-placeholder-idle": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "input-date-picker-global-required": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-date-picker-global-value-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-date-picker-global-value-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-date-picker-global-value-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-date-picker-error-error-msg": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-date-picker-normal-description-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-date-picker-normal-description-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "input-date-picker-normal-description-idle": "light-dark(rgb(109 114 120), rgb(109 114 120))"
      },
      "borderColor": {
        "input-date-picker-error-box-border-color-active": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-date-picker-error-box-border-color-hover": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-date-picker-error-box-border-color-idle": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-date-picker-normal-box-border-color-active": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "input-date-picker-normal-box-border-color-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "input-date-picker-normal-box-border-color-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "input-date-picker-normal-box-border-color-idle": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fill": {
        "input-date-picker-error-icon-hover": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-date-picker-error-icon-idle": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-date-picker-normal-icon-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "input-date-picker-normal-icon-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "input-date-picker-normal-icon-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))"
      },
      "fontFamily": {
        "input-date-picker-global-label-text-style": "Inter, system-ui, sans-serif",
        "input-date-picker-global-placeholder-text-style": "Inter, system-ui, sans-serif",
        "input-date-picker-global-required-text-style": "Inter, system-ui, sans-serif",
        "input-date-picker-global-separator-text-style": "Inter, system-ui, sans-serif",
        "input-date-picker-global-value-text-style": "Inter, system-ui, sans-serif",
        "input-date-picker-error-error-msg-text-style": "Inter, system-ui, sans-serif",
        "input-date-picker-normal-description-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "input-date-picker-global-label-text-style": [
          "14px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-date-picker-global-placeholder-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-date-picker-global-required-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-date-picker-global-separator-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-date-picker-global-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-date-picker-error-error-msg-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-date-picker-normal-description-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "input-date-picker-global-box-border-width": "1px",
        "input-date-picker-global-box-gap": "12px",
        "input-date-picker-global-box-gap-range": "8px",
        "input-date-picker-global-box-height": "32px",
        "input-date-picker-global-box-padding-x": "12px",
        "input-date-picker-global-box-padding-y": "4px",
        "input-date-picker-global-container-gap": "4px",
        "input-date-picker-global-container-width-min": "128px",
        "input-date-picker-global-container-label-gap": "4px"
      },
      "borderRadius": {
        "input-date-picker-global-box-border-radius": "4px"
      }
    },
  },
};
