// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: InputSearch
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "input-search-box-disabled": "light-dark(rgb(248 250 252), rgb(24 25 27))",
        "input-search-box-hover": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "input-search-box-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "input-search-placeholder-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-search-placeholder-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "input-search-placeholder-idle": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "input-search-required": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-search-value-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-search-value-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-search-value-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "input-search-border-color-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "input-search-border-color-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "input-search-border-color-idle": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fill": {
        "input-search-clear-icon": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "input-search-icon-search-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "input-search-icon-search-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "input-search-icon-search-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))"
      },
      "fontFamily": {
        "input-search-label-text-style": "Inter, system-ui, sans-serif",
        "input-search-required-text-style": "Inter, system-ui, sans-serif",
        "input-search-value-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "input-search-label-text-style": [
          "14px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-search-required-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-search-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "input-search-box-border-width": "1px",
        "input-search-box-gap": "8px",
        "input-search-box-height": "32px",
        "input-search-box-padding-x": "12px",
        "input-search-box-padding-y": "4px",
        "input-search-container-gap": "4px",
        "input-search-container-width-min": "128px",
        "input-search-container-label-gap": "4px"
      },
      "borderRadius": {
        "input-search-box-border-radius": "4px"
      }
    },
  },
};
