// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: Link
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "fill": {
        "link-external-icon-active": "light-dark(rgb(6 54 121), rgb(190 215 244))",
        "link-external-icon-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "link-external-icon-hover": "light-dark(rgb(19 84 174), rgb(23 99 207))",
        "link-external-icon-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))"
      },
      "fontFamily": {
        "link-text-style-active": "Inter, system-ui, sans-serif",
        "link-text-style-disabled": "Inter, system-ui, sans-serif",
        "link-text-style-hover": "Inter, system-ui, sans-serif",
        "link-text-style-idle": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "link-text-style-active": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-text-style-disabled": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-text-style-hover": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-text-style-idle": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "link-container-gap": "4px",
        "link-container-height": "32px"
      }
    },
  },
};
