// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: SidebarSecondary
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "sidebar-secondary-menu-item-selected-container-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "sidebar-secondary-menu-item-selected-container-hover": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "sidebar-secondary-menu-item-selected-container-idle": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "sidebar-secondary-menu-item-unselected-container-active": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "sidebar-secondary-menu-item-unselected-container-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "sidebar-secondary-menu-item-unselected-container-idle": "light-dark(rgb(248 250 252), rgb(24 25 27))",
        "sidebar-secondary-global-container": "light-dark(rgb(248 250 252), rgb(24 25 27))"
      },
      "textColor": {
        "sidebar-secondary-menu-item-global-label": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-secondary-menu-item-extras-global-shortcut": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "sidebar-secondary-section-label-section": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-secondary-global-header-label": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-secondary-collapsed-breadcrumb-label": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "sidebar-secondary-collapsed-label-current-page": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "sidebar-secondary-global-container-border-color": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "sidebar-secondary-global-container-footer-border-color": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fill": {
        "sidebar-secondary-menu-item-global-icon": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "sidebar-secondary-menu-item-extras-global-external-icon": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "sidebar-secondary-section-icon-arrow": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "sidebar-secondary-collapsed-icon-separator": "light-dark(rgb(201 204 207), rgb(73 76 80))"
      },
      "fontFamily": {
        "sidebar-secondary-menu-item-global-label-text-style": "Inter, system-ui, sans-serif",
        "sidebar-secondary-menu-item-extras-global-shortcut-text-style": "Inter, system-ui, sans-serif",
        "sidebar-secondary-section-label-section-text-style": "Inter, system-ui, sans-serif",
        "sidebar-secondary-global-header-label-text-style": "Inter, system-ui, sans-serif",
        "sidebar-secondary-collapsed-breadcrumb-label-text-style": "Inter, system-ui, sans-serif",
        "sidebar-secondary-collapsed-label-current-page-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "sidebar-secondary-menu-item-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "sidebar-secondary-menu-item-extras-global-shortcut-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "sidebar-secondary-section-label-section-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "sidebar-secondary-global-header-label-text-style": [
          "24px",
          {
            "lineHeight": "32px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "sidebar-secondary-collapsed-breadcrumb-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "sidebar-secondary-collapsed-label-current-page-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "sidebar-secondary-menu-item-global-container-gap": "8px",
        "sidebar-secondary-menu-item-global-container-height-min": "40px",
        "sidebar-secondary-menu-item-global-container-padding-x": "16px",
        "sidebar-secondary-menu-item-global-container-padding-y": "8px",
        "sidebar-secondary-menu-item-global-icon-margin-t": "4px",
        "sidebar-secondary-menu-item-global-icon-size": "16px",
        "sidebar-secondary-menu-item-extras-global-container-gap": "8px",
        "sidebar-secondary-menu-item-extras-global-external-icon-size": "16px",
        "sidebar-secondary-section-menu-item-list-gap": "0px",
        "sidebar-secondary-section-container-padding-y": "0px",
        "sidebar-secondary-section-container-header-gap": "8px",
        "sidebar-secondary-section-container-header-min-width": "undefinedundefined",
        "sidebar-secondary-section-container-header-padding-x": "16px",
        "sidebar-secondary-section-container-header-padding-y": "2px",
        "sidebar-secondary-global-container-border-width": "1px",
        "sidebar-secondary-global-container-footer-border-width": "1px",
        "sidebar-secondary-global-container-header-padding-x": "16px",
        "sidebar-secondary-global-container-header-padding-y": "12px",
        "sidebar-secondary-global-section-list-gap": "0px",
        "sidebar-secondary-collapsed-container-width": "48px",
        "sidebar-secondary-collapsed-container-content-gap": "4px",
        "sidebar-secondary-collapsed-container-content-padding-y": "16px",
        "sidebar-secondary-collapsed-container-header-padding-x": "8px",
        "sidebar-secondary-collapsed-container-header-padding-y": "16px",
        "sidebar-secondary-collapsed-icon-separator-size": "16px",
        "sidebar-secondary-expanded-container-width": "256px",
        "sidebar-secondary-expanded-container-header-padding-x": "16px",
        "sidebar-secondary-expanded-container-header-padding-y": "8px"
      }
    },
  },
};
