// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: SidebarPrimary
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "sidebar-primary-menu-item-selected-container-active": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "sidebar-primary-menu-item-selected-container-hover": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "sidebar-primary-menu-item-selected-container-idle": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "sidebar-primary-menu-item-unselected-container-active": "light-dark(rgb(3 43 99), rgb(61 63 67))",
        "sidebar-primary-menu-item-unselected-container-hover": "light-dark(rgb(3 43 99), rgb(61 63 67))",
        "sidebar-primary-menu-item-unselected-container-idle": "light-dark(rgb(0 32 77), rgb(12 12 14))",
        "sidebar-primary-global-container": "light-dark(rgb(0 32 77), rgb(12 12 14))"
      },
      "textColor": {
        "sidebar-primary-menu-item-selected-label-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-primary-menu-item-selected-label-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-primary-menu-item-selected-label-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-primary-menu-item-unselected-label-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-primary-menu-item-unselected-label-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-primary-menu-item-unselected-label-idle": "light-dark(rgb(255 255 255 / 0.6), rgb(255 255 255 / 0.502))",
        "sidebar-primary-menu-item-extras-global-shortcut": "light-dark(rgb(255 255 255 / 0.6), rgb(255 255 255 / 0.502))"
      },
      "borderColor": {
        "sidebar-primary-section-container-border-color": "light-dark(rgb(255 255 255 / 0.102), rgb(255 255 255 / 0.102))",
        "sidebar-primary-global-container-footer-border-color": "light-dark(rgb(255 255 255 / 0.102), rgb(255 255 255 / 0.102))"
      },
      "fill": {
        "sidebar-primary-menu-item-selected-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-primary-menu-item-selected-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-primary-menu-item-selected-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-primary-menu-item-unselected-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-primary-menu-item-unselected-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-primary-menu-item-unselected-icon-idle": "light-dark(rgb(255 255 255 / 0.6), rgb(255 255 255 / 0.502))",
        "sidebar-primary-menu-item-extras-global-external-icon": "light-dark(rgb(255 255 255 / 0.6), rgb(255 255 255 / 0.502))",
        "sidebar-primary-global-logo": "light-dark(rgb(255 255 255), rgb(255 255 255))"
      },
      "fontFamily": {
        "sidebar-primary-menu-item-global-label-text-style": "Inter, system-ui, sans-serif",
        "sidebar-primary-menu-item-extras-global-shortcut-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "sidebar-primary-menu-item-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "sidebar-primary-menu-item-extras-global-shortcut-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "sidebar-primary-menu-item-global-container-gap": "8px",
        "sidebar-primary-menu-item-global-container-height": "40px",
        "sidebar-primary-menu-item-global-container-padding-x": "16px",
        "sidebar-primary-menu-item-global-container-padding-y": "8px",
        "sidebar-primary-menu-item-global-icon-margin-t": "4px",
        "sidebar-primary-menu-item-global-icon-size": "16px",
        "sidebar-primary-menu-item-extras-global-container-gap": "8px",
        "sidebar-primary-menu-item-extras-global-external-icon-size": "16px",
        "sidebar-primary-section-menu-item-list-gap": "0px",
        "sidebar-primary-section-container-border-width": "1px",
        "sidebar-primary-section-container-padding-y": "8px",
        "sidebar-primary-global-container-footer-border-width": "1px",
        "sidebar-primary-global-footer-list-gap": "0px",
        "sidebar-primary-global-section-list-gap": "0px",
        "sidebar-primary-collapsed-container-width": "48px",
        "sidebar-primary-collapsed-container-header-padding-x": "8px",
        "sidebar-primary-collapsed-container-header-padding-y": "16px",
        "sidebar-primary-collapsed-logo-height": "32px",
        "sidebar-primary-expanded-container-width": "256px",
        "sidebar-primary-expanded-container-header-padding-x": "16px",
        "sidebar-primary-expanded-container-header-padding-y": "8px",
        "sidebar-primary-expanded-logo-height": "48px"
      }
    },
  },
};
