// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: Switch
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "switch-global-tick-active": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "switch-global-tick-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "switch-global-tick-hover": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "switch-global-tick-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "switch-off-box-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "switch-off-box-disabled": "light-dark(rgb(248 250 252), rgb(24 25 27))",
        "switch-off-box-hover": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "switch-off-box-idle": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "switch-on-box-active": "light-dark(rgb(70 185 89), rgb(70 185 89))",
        "switch-on-box-disabled": "light-dark(rgb(248 250 252), rgb(24 25 27))",
        "switch-on-box-hover": "light-dark(rgb(70 185 89), rgb(70 185 89))",
        "switch-on-box-idle": "light-dark(rgb(70 185 89), rgb(70 185 89))"
      },
      "textColor": {
        "switch-global-label": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "switch-global-box-border-color-active": "light-dark(transparent, transparent)",
        "switch-global-box-border-color-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "switch-global-box-border-color-hover": "light-dark(transparent, transparent)",
        "switch-global-box-border-color-idle": "light-dark(transparent, transparent)"
      },
      "fontFamily": {
        "switch-global-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "switch-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "switch-global-box-border-width": "1px",
        "switch-global-box-height": "16px",
        "switch-global-box-padding-x": "2px",
        "switch-global-box-padding-y": "2px",
        "switch-global-box-width": "32px",
        "switch-global-container-gap": "8px",
        "switch-global-tick-size": "12px"
      },
      "borderRadius": {
        "switch-global-box-border-radius": "999px",
        "switch-global-tick-border-radius": "999px"
      }
    },
  },
};
