// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • component: Tooltip
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "tooltip-container": "light-dark(rgb(25 27 35), rgb(255 255 255))"
      },
      "textColor": {
        "tooltip-label": "light-dark(rgb(255 255 255), rgb(24 25 27))"
      },
      "fontFamily": {
        "tooltip-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "tooltip-label-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "tooltip-container-padding-x": "12px",
        "tooltip-container-padding-y": "8px",
        "tooltip-container-width-max": "256px",
        "tooltip-container-width-min": "48px"
      },
      "borderRadius": {
        "tooltip-container-border-radius": "4px"
      }
    },
  },
};
