// React code generator. Emits one `.tsx` per asset id. With lossless resize, an
// asset's size variants share identical inner geometry — they differ only in the
// root width/height and (mono/stroke) a uniform stroke-width that we lift to the
// root. So each unique `<svg>` geometry is emitted ONCE as a constant and reused
// across sizes (and, for the merged icons group, across styles); the component
// clones it per render with the size's width/height/strokeWidth and any forwarded
// props (mirrors the legacy kit's BaseIcon clone). A hand-authored size override
// (different markup) naturally falls into its own geometry constant.
//
// Two shapes:
//   - hasVariantAxis  → `variant` (style, e.g. stroke-mono) + `size` props (icons).
//   - single style    → `size` prop only (concept-pack).

import { parseSvg, walk, type INode } from '../svg-ast';
import { nodeToJsx, pascalCase, styleLabel } from './naming';

interface VariantInput {
  /** Variant id (= size key, e.g. `"24"`, `"dark"`). */
  size: string;
  /** Optimized SVG for this variant. */
  svg: string;
}

export interface StyleInput {
  /** Source pack name (the style); ignored when `hasVariantAxis` is false. */
  style: string;
  /** Effective canonical variant id (the preselected size). */
  canonical: string;
  variants: VariantInput[];
}

export interface ComponentInput {
  id: string;
  hasVariantAxis: boolean;
  styles: StyleInput[];
}

export interface GeneratedComponent {
  /** PascalCase stem — the on-disk file name matches the component (e.g. `IconBasic`). */
  fileName: string;
  componentName: string;
  /** Original kebab-case asset id (for the barrel's `assetIds`). */
  id: string;
  source: string;
}

/** Default style precedence when an icon exists in several packs. */
const STYLE_PRECEDENCE = ['stroke-mono', 'solid-mono', 'stroke-multi', 'solid-multi'];

const isStroked = (node: INode): boolean =>
  node.attributes.stroke != null && node.attributes.stroke !== 'none';

interface ProcessedVariant {
  size: string;
  geomJsx: string;
  w: string;
  h: string;
  sw?: string;
}

/** Strip root width/height (and a uniform stroke-width) so geometry dedups across sizes. */
function processVariant(input: VariantInput): ProcessedVariant {
  const root = parseSvg(input.svg);
  const w = root.attributes.width ?? '';
  const h = root.attributes.height ?? '';
  delete root.attributes.width;
  delete root.attributes.height;

  const widths = new Set<string>();
  walk(root, (node) => {
    if (isStroked(node) && node.attributes['stroke-width']) widths.add(node.attributes['stroke-width']);
  });
  const lift = widths.size === 1 ? [...widths][0] : undefined;
  const skip = lift ? new Set(['stroke-width']) : new Set<string>();

  return { size: input.size, geomJsx: nodeToJsx(root, skip), w, h, sw: lift };
}

const sizeKey = (s: string): string => (/^[0-9][a-z0-9-]*$/i.test(s) ? `'${s}'` : JSON.stringify(s));

const specLiteral = (geomVar: string, v: ProcessedVariant): string =>
  `{ g: ${geomVar}, w: ${JSON.stringify(v.w)}, h: ${JSON.stringify(v.h)}${v.sw != null ? `, sw: ${JSON.stringify(v.sw)}` : ''} }`;

export function generateComponent(input: ComponentInput): GeneratedComponent {
  const componentName = pascalCase(input.id);

  // Component-wide geometry dedup: identical geometry JSX → one constant.
  const geomNames = new Map<string, string>();
  const geomConsts: string[] = [];
  const geomVar = (jsx: string): string => {
    let name = geomNames.get(jsx);
    if (!name) {
      name = `g${geomNames.size}`;
      geomNames.set(jsx, name);
      geomConsts.push(`const ${name} = (\n  ${jsx}\n);`);
    }
    return name;
  };

  const cloneBody = [
    'React.cloneElement(spec.g, {',
    '    ref,',
    '    width: spec.w,',
    '    height: spec.h,',
    '    ...(spec.sw != null ? { strokeWidth: spec.sw } : {}),',
    '    ...props,',
    '  })',
  ].join('\n  ');

  if (!input.hasVariantAxis) {
    const style = input.styles[0];
    const processed = style.variants.map(processVariant);
    const sizes = processed
      .map((v) => `    ${sizeKey(v.size)}: ${specLiteral(geomVar(v.geomJsx), v)},`)
      .join('\n');
    const sizeUnion = processed.map((v) => `'${v.size}'`).join(' | ');

    const source = `/* eslint-disable */
// AUTO-GENERATED by @spec-lab/style-dictionary — do not edit.
import * as React from 'react';

${geomConsts.join('\n\n')}

export type ${componentName}Size = ${sizeUnion};

export interface ${componentName}Props extends Omit<React.SVGProps<SVGSVGElement>, 'children'> {
  size?: ${componentName}Size;
}

interface Spec { g: React.ReactElement<React.SVGProps<SVGSVGElement>>; w: string; h: string; sw?: string }

const SIZES: Record<string, Spec> = {
${sizes}
};

const DEFAULT_SIZE: ${componentName}Size = '${style.canonical}';

export const ${componentName} = React.forwardRef<SVGSVGElement, ${componentName}Props>(
  ({ size, ...props }, ref) => {
    const spec = SIZES[size ?? DEFAULT_SIZE] ?? SIZES[DEFAULT_SIZE];
    return ${cloneBody};
  },
);
${componentName}.displayName = '${componentName}';
`;
    return { fileName: componentName, componentName, id: input.id, source };
  }

  // Variant axis: merge styles, each with its own sizes.
  const labelled = input.styles
    .map((s) => ({ ...s, label: styleLabel(s.style) }))
    .sort((a, b) => STYLE_PRECEDENCE.indexOf(a.label) - STYLE_PRECEDENCE.indexOf(b.label));

  const styleEntries = labelled
    .map((s) => {
      const processed = s.variants.map(processVariant);
      const sizes = processed
        .map((v) => `      ${sizeKey(v.size)}: ${specLiteral(geomVar(v.geomJsx), v)},`)
        .join('\n');
      return `  '${s.label}': {\n    default: '${s.canonical}',\n    sizes: {\n${sizes}\n    },\n  },`;
    })
    .join('\n');

  const variantUnion = labelled.map((s) => `'${s.label}'`).join(' | ');
  const sizeUnion = [...new Set(labelled.flatMap((s) => s.variants.map((v) => `'${v.size}'`)))].join(' | ');
  const defaultVariant = labelled[0].label;

  const source = `/* eslint-disable */
// AUTO-GENERATED by @spec-lab/style-dictionary — do not edit.
import * as React from 'react';

${geomConsts.join('\n\n')}

export type ${componentName}Variant = ${variantUnion};
export type ${componentName}Size = ${sizeUnion};

export interface ${componentName}Props extends Omit<React.SVGProps<SVGSVGElement>, 'children'> {
  variant?: ${componentName}Variant;
  size?: ${componentName}Size;
}

interface Spec { g: React.ReactElement<React.SVGProps<SVGSVGElement>>; w: string; h: string; sw?: string }

const STYLES: Record<${componentName}Variant, { default: string; sizes: Record<string, Spec> }> = {
${styleEntries}
};

const DEFAULT_VARIANT: ${componentName}Variant = '${defaultVariant}';

export const ${componentName} = React.forwardRef<SVGSVGElement, ${componentName}Props>(
  ({ variant = DEFAULT_VARIANT, size, ...props }, ref) => {
    const style = STYLES[variant];
    const spec = style.sizes[size ?? style.default] ?? style.sizes[style.default];
    return ${cloneBody};
  },
);
${componentName}.displayName = '${componentName}';
`;
  return { fileName: componentName, componentName, id: input.id, source };
}

/** Barrel for a react/ dir: re-export every component + an `assetIds` array. */
export function generateBarrel(components: GeneratedComponent[]): string {
  const exports = components.map((c) => `export * from './${c.fileName}';`).join('\n');
  const ids = components.map((c) => `'${c.id}'`).join(', ');
  return `/* eslint-disable */
// AUTO-GENERATED by @spec-lab/style-dictionary — do not edit.
${exports}

export const assetIds = [${ids}] as const;
`;
}
