blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/acronis/ui-component-library/discussions
    about: For questions, ideas, and general discussion please use GitHub Discussions.
