<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    class="acv-icon"
    viewBox="0 0 16 16"
  >
    <circle
      cx="4"
      cy="8"
      r="4"
      fill="#24AEE2"
    />
    <circle
      cx="4"
      cy="8"
      r="3.5"
      stroke="#243143"
      stroke-opacity=".1"
    />
  </svg>
</template>
