import type { KitRule } from '../types';

export const anatomyRules = [
  {
    id: 'anatomy/focus-ring-parity',
    title: 'One focus-ring treatment',
    category: 'anatomy',
    severity: 'must',
    rule: 'Every focusable component uses the same focus-ring treatment: the shared focus token, width, and offset.',
    rationale: 'Divergent focus rings make keyboard navigation feel inconsistent and look unmaintained.',
    checklist: 'A1',
    detector: 'kit-lint/focus-ring',
    tokens: ['--ui-focus-brand'],
    wcag: ['2.4.7'],
    relatedRules: ['accessibility/accessible-name'],
  },
  {
    id: 'anatomy/disabled-parity',
    title: 'One disabled treatment',
    category: 'anatomy',
    severity: 'should',
    rule: 'Disabled states use the same treatment across components (a disabled token, not ad-hoc opacity).',
    rationale: 'Inconsistent disabled styling makes equivalent states look different.',
    checklist: 'A2',
    detector: 'screen/disabled-treatment',
  },
  {
    id: 'anatomy/explicit-border-color',
    title: 'Explicit border color',
    category: 'anatomy',
    severity: 'should',
    rule: 'Use `border-border` (or a real token), never the bare `border` utility, which renders transparent/currentColor in ui-react.',
    rationale: 'Bare `border` silently produces an invisible or wrong-colored edge.',
    checklist: 'A3',
    detector: 'kit-lint/border-border',
    tokens: ['--ui-border-on-surface-border'],
  },
  {
    id: 'anatomy/parts-match-spec',
    title: 'Parts match the spec anatomy',
    category: 'anatomy',
    severity: 'must',
    rule: 'Every part declared in a component spec anatomy must exist in the implementation, and vice versa.',
    rationale: 'A missing/extra part means the spec and the component have drifted.',
    checklist: 'A4',
    detector: 'spec/anatomy-parts',
  },
  {
    id: 'anatomy/data-states-present',
    title: 'Data components cover their states',
    category: 'anatomy',
    severity: 'should',
    rule: 'A component that renders data provides empty, loading, and error treatments.',
    rationale: 'Missing states are where real apps look broken; they must be designed, not improvised.',
    checklist: 'A5',
    detector: 'spec/data-states',
  },
  {
    id: 'anatomy/empty-skeleton-parity',
    title: 'Consistent empty/skeleton composition',
    category: 'anatomy',
    severity: 'should',
    rule: 'Empty states and skeletons share one composition across the kit (icon + title + description + optional action; matching skeleton shimmer).',
    rationale: 'Divergent empty/loading states are jarring when a user moves between screens.',
    checklist: 'A6',
    detector: 'screen/empty-skeleton-parity',
    relatedRules: ['anatomy/data-states-present'],
  },
] satisfies KitRule[];
