import type { KitRule } from '../types';

export const compositionRules = [
  {
    id: 'composition/vertical-rhythm',
    title: 'Consistent vertical rhythm',
    category: 'composition',
    severity: 'should',
    rule: 'Gaps between sections/regions on a screen come from the spacing scale and repeat consistently.',
    rationale: 'Irregular section gaps make an assembled screen feel arbitrary.',
    checklist: 'C1',
    detector: 'screen/vertical-rhythm',
    relatedRules: ['spacing/on-grid'],
  },
  {
    id: 'composition/edge-baseline-alignment',
    title: 'Edges and baselines align',
    category: 'composition',
    severity: 'should',
    rule: 'Adjacent components align on their edges and text baselines (no near-misses off by a few px).',
    rationale: 'Sub-pixel misalignment is the subtle defect humans feel but rarely name.',
    checklist: 'C2',
    detector: 'screen/alignment-grid',
  },
  {
    id: 'composition/shared-grid',
    title: 'Components share the layout grid',
    category: 'composition',
    severity: 'should',
    rule: 'Components on a screen snap to a shared column/alignment grid.',
    rationale: 'A shared grid is what makes a screen read as designed rather than assembled.',
    checklist: 'C3',
    detector: 'screen/shared-grid',
    relatedRules: ['composition/edge-baseline-alignment'],
  },
  {
    id: 'composition/variant-parity',
    title: 'One look per role across screens',
    category: 'composition',
    severity: 'must',
    rule: 'The same role (the primary action, the destructive action, a section header…) uses the same component + variant on every screen.',
    rationale: 'A primary action that looks different across screens erodes trust and learnability.',
    checklist: 'C4',
    detector: 'ref/variant-parity',
    relatedRules: ['tokens/one-token-per-role'],
  },
  {
    id: 'composition/z-index-layers',
    title: 'Z-index from the layer scale',
    category: 'composition',
    severity: 'must',
    rule: 'Stacking uses the defined layer scale (base/sticky/overlay/drawer/modal/popover/alert), never ad-hoc z-index.',
    rationale: 'Ad-hoc z-index causes overlays to fight and render in the wrong order.',
    checklist: 'C5',
    detector: 'kit-lint/z-index',
  },
  {
    id: 'composition/single-solution-per-job',
    title: 'One solution per job on a screen',
    category: 'composition',
    severity: 'should',
    rule: 'A screen should not solve the same job two different ways (two filter affordances, two table styles).',
    rationale: 'Redundant, divergent affordances confuse users and signal an unowned design.',
    checklist: 'C6',
    detector: 'ai/single-solution',
  },
  {
    id: 'composition/density-parity',
    title: 'Consistent density',
    category: 'composition',
    severity: 'may',
    rule: 'Co-located regions share a density (a compact table should not sit beside a roomy form without intent).',
    rationale: 'Density whiplash within one screen feels unbalanced.',
    checklist: 'C7',
    detector: 'ai/density-parity',
  },
  {
    id: 'composition/no-clipping',
    title: 'No reserved-gutter clipping',
    category: 'composition',
    severity: 'should',
    rule: 'Scroll containers and overlays must not reserve a gutter that clips full-bleed content (e.g. a scrollbar cropping a selected row).',
    rationale: 'A real defect found this session: a native scrollbar gutter cropped the full-width selected sidebar row.',
    checklist: 'C8',
    detector: 'screen/reserved-gutter',
  },
] satisfies KitRule[];
