// JS output (`js/tokens.js` + `.d.ts`): a map of every generated token name to
// its `var(--<name>)` reference, for CSS-in-JS / inline-style consumers. Values
// are references (not resolved colors), so brand (`[data-brand]`) and theme
// (`[data-theme]`) overrides still resolve at paint — the same guarantee the CSS
// gives. Keyed by the `--ui-*` name (without the leading `--`).

import {
  type StyleModel,
  type WriteFile,
} from './hooks/formats/css-light-dark';
import { jsTokensDtsFile, jsTokensFile } from './platforms';

/** Every `--ui-*` name defined anywhere in the model, sorted. */
const allNames = (model: StyleModel): string[] => {
  const names = new Set<string>(model.primitives.vars.keys());
  for (const { base, overrides } of model.slices) {
    for (const name of base.vars.keys()) names.add(name);
    for (const o of overrides)
      for (const name of o.vars.keys()) names.add(name);
  }
  return [...names].sort((a, b) => a.localeCompare(b));
};

export function emitJs(model: StyleModel, write: WriteFile): void {
  const names = allNames(model);
  const entries = names
    .map((name) => `  ${JSON.stringify(name)}: "var(--${name})",`)
    .join('\n');

  write(
    jsTokensFile(),
    `// Generated by @constructor-lab/style-dictionary — DO NOT EDIT.\n` +
      `// Source: @constructor-lab/design-tokens • token name → var() reference.\n\n` +
      `export const tokens = {\n${entries}\n};\n`
  );

  write(
    jsTokensDtsFile(),
    `// Generated by @constructor-lab/style-dictionary — DO NOT EDIT.\n` +
      `export declare const tokens: Record<string, string>;\n`
  );
}
