// SCSS output (`scss/`): a mirror of the token layer as a reusable mixin, so a
// Sass consumer gets the same compact, reference-based tokens via `@include`
// (the ergonomic the legacy kit's theme mixins use) instead of a raw `@import`.
//
//   scss/_tokens.scss  — `@mixin ui-tokens` wrapping every generated rule
//                        (primitives theme layer + semantics + components + brand
//                        overrides), body identical to the css bundle.
//   scss/_mixins.scss  — forwards `ui-tokens` and exposes `ui-theme` for a plain
//                        top-level `@include`.

import {
  serializeSlice,
  type StyleModel,
  type WriteFile,
} from './hooks/formats/css-light-dark';
import { scssMixinsFile, scssTokensFile } from './platforms';

/** Drop the two-line generated-file header a serialized slice starts with. */
const stripHeader = (css: string): string => {
  const blank = css.indexOf('\n\n');
  return blank === -1 ? css.trimEnd() : css.slice(blank + 2).trimEnd();
};

const indent = (block: string): string =>
  block
    .split('\n')
    .map((line) => (line.length ? `  ${line}` : line))
    .join('\n');

export function emitScss(model: StyleModel, write: WriteFile): void {
  const sections = [
    serializeSlice({
      tier: 'primitives',
      themeLayer: true,
      base: model.primitives,
      overrides: [],
    }),
    ...model.slices.map(({ tier, base, overrides }) =>
      serializeSlice({ tier, themeLayer: false, base, overrides })
    ),
  ]
    .map(stripHeader)
    .join('\n\n');

  write(
    scssTokensFile(),
    `// Generated by @spec-lab/style-dictionary — DO NOT EDIT.\n` +
      `// Source: @spec-lab/design-tokens • the full token layer as a mixin.\n\n` +
      `@mixin ui-tokens {\n${indent(sections)}\n}\n`
  );

  write(
    scssMixinsFile(),
    `// Generated by @spec-lab/style-dictionary — DO NOT EDIT.\n` +
      `// Reusable token mixins. Usage:\n` +
      `//   @use '@spec-lab/tokens/scss/mixins' as tokens;\n` +
      `//   @include tokens.ui-theme;\n\n` +
      `@forward 'tokens';\n` +
      `@use 'tokens';\n\n` +
      `// Stamp the whole token layer (primitives + semantics + components + brands).\n` +
      `@mixin ui-theme {\n  @include tokens.ui-tokens;\n}\n`
  );
}
