import { createRequire } from 'node:module';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { toComponentName } from '../src/lib/naming.ts';
import {
  ICON_SIZES,
  PACKS,
  STROKE_WIDTH_PX,
  type PackConfig,
} from './packs.ts';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const srcPacks = resolve(here, '..', 'src', 'packs');

// icons-svg ships flat SVG masters (src/svg) + per-pack/category name-list
// manifests (src/figma). Resolve its root from the package.json export.
const nextRoot = dirname(require.resolve('@spec-lab/icons-svg/package.json'));
const svgDir = resolve(nextRoot, 'src', 'svg');
const figmaDir = resolve(nextRoot, 'src', 'figma');

function round(n: number): number {
  return Math.round(n * 1000) / 1000;
}

/** Manifest files feeding a pack: `<name>.json` or `<name>-<category>.json`. */
function manifestMatcher(pack: PackConfig): RegExp {
  return new RegExp(`^${pack.name}(-.*)?\\.json$`);
}

/** kebab-attr="…" → camelAttr="…" for JSX (leaving aria- and data- attrs alone). */
function camelCaseAttrs(s: string): string {
  return s.replace(/\s([a-zA-Z][\w]*(?:-[\w]+)+)=/g, (match, name: string) => {
    if (/^(aria|data)-/.test(name)) return match;
    return (
      ' ' + name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()) + '='
    );
  });
}

/** Prefix gradient/clip ids (and their url(#…) refs) to avoid cross-icon collisions. */
function namespaceIds(s: string, slug: string): string {
  return s
    .replace(/\bid="([^"]+)"/g, (_, id: string) => `id="${slug}-${id}"`)
    .replace(/url\(#([^)]+)\)/g, (_, id: string) => `url(#${slug}-${id})`);
}

/** Strip a 24px master SVG down to JSX-ready inner markup per the pack config. */
function toInnerJsx(svg: string, pack: PackConfig, slug: string): string {
  let out = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i)?.[1] ?? '';
  if (!pack.multicolor) {
    // mono → drop authored colors so the <svg>'s currentColor takes over.
    out = out.replace(/\sstroke="[^"]*"/g, '').replace(/\sfill="[^"]*"/g, '');
  } else {
    // multicolor → keep colors, but namespace ids so gradients don't clash.
    out = namespaceIds(out, slug);
  }
  if (pack.paint === 'stroke') {
    // stroke width + line caps come from the <svg> (rule-driven / round).
    out = out
      .replace(/\sstroke-width="[^"]*"/g, '')
      .replace(/\sstroke-linecap="[^"]*"/g, '')
      .replace(/\sstroke-linejoin="[^"]*"/g, '');
  }
  out = camelCaseAttrs(out);
  return out
    .split(/(?<=\/>|>)\s*(?=<)/)
    .map((line) => line.trim())
    .filter(Boolean)
    .join('\n      ');
}

function wrapperSource(
  pack: PackConfig,
  strokeMap: Record<number, number>
): string {
  const head =
    `// Generated by scripts/generate-icons.ts. Do not edit.\n` +
    `import { SvgIcon, type IconProps, type SvgIconProps } from '../../lib/svg-icon';\n\n` +
    `export type { IconProps };\n\n`;
  const props = `props: Omit<SvgIconProps, 'strokeWidthBySize'>`;
  if (pack.paint === 'stroke') {
    // mono forces currentColor; multicolor keeps each path's authored stroke.
    const stroke = pack.multicolor ? '' : ' stroke="currentColor"';
    return (
      head +
      `const STROKE_WIDTH_BY_SIZE: Record<number, number> = ${JSON.stringify(strokeMap)};\n\n` +
      `export function PackIcon(${props}) {\n` +
      `  return (\n` +
      `    <SvgIcon\n` +
      `      fill="none"${stroke}\n` +
      `      strokeLinecap="round"\n` +
      `      strokeLinejoin="round"\n` +
      `      strokeWidthBySize={STROKE_WIDTH_BY_SIZE}\n` +
      `      {...props}\n` +
      `    />\n  );\n}\n`
    );
  }
  // solid
  const fill = pack.multicolor ? '' : ' fill="currentColor"';
  return (
    head +
    `export function PackIcon(${props}) {\n` +
    `  return <SvgIcon${fill} {...props} />;\n}\n`
  );
}

/** Merge + de-dupe the icon names for a pack from its manifest file(s). */
async function packIconNames(pack: PackConfig): Promise<string[]> {
  const matcher = manifestMatcher(pack);
  const files = (await readdir(figmaDir))
    .filter((f) => f !== 'icons.json' && matcher.test(f))
    .sort();
  const names = new Set<string>();
  for (const file of files) {
    const list = JSON.parse(
      await readFile(resolve(figmaDir, file), 'utf8')
    ) as string[];
    list.forEach((name) => names.add(name));
  }
  return [...names].sort();
}

async function generatePack(pack: PackConfig): Promise<number> {
  const names = await packIconNames(pack);

  const outDir = resolve(srcPacks, pack.name);
  await rm(outDir, { recursive: true, force: true });
  await mkdir(resolve(outDir, 'icons'), { recursive: true });

  let viewBoxSize = 24;
  const components: { name: string; component: string; file: string }[] = [];
  for (const assetName of names) {
    let svg: string;
    try {
      svg = await readFile(resolve(svgDir, `${assetName}.svg`), 'utf8');
    } catch {
      console.warn(
        `⚠ icons-react: ${pack.name} — no SVG for "${assetName}", skipping`
      );
      continue;
    }
    const viewBox = svg.match(/viewBox="([^"]*)"/)?.[1] ?? '0 0 24 24';
    viewBoxSize = Number(viewBox.split(/\s+/)[2]) || viewBoxSize;

    const component = toComponentName(assetName);
    const inner = toInnerJsx(svg, pack, assetName);
    const body =
      `import { PackIcon, type IconProps } from '../icon';\n\n` +
      `export function ${component}(props: IconProps) {\n` +
      `  return (\n    <PackIcon viewBox="${viewBox}" {...props}>\n      ${inner}\n    </PackIcon>\n  );\n}\n`;
    await writeFile(resolve(outDir, 'icons', `${assetName}.tsx`), body);
    components.push({
      name: assetName,
      component,
      file: `./icons/${assetName}`,
    });
  }

  // Stroke-width map (stroke packs only): rendered px → viewBox user units.
  const strokeMap: Record<number, number> = {};
  if (pack.paint === 'stroke') {
    for (const size of ICON_SIZES) {
      strokeMap[size] = round((STROKE_WIDTH_PX[size] * viewBoxSize) / size);
    }
  }

  await writeFile(resolve(outDir, 'icon.tsx'), wrapperSource(pack, strokeMap));

  const imports = components
    .map((c) => `import { ${c.component} } from '${c.file}';`)
    .join('\n');
  const exportList = `export {\n${components.map((c) => `  ${c.component},`).join('\n')}\n};`;
  const registry =
    `export const icons = {\n` +
    components.map((c) => `  '${c.name}': ${c.component},`).join('\n') +
    `\n} as const;`;
  const index =
    `// Generated by scripts/generate-icons.ts from @spec-lab/icons-svg. Do not edit.\n` +
    `export type { IconProps } from './icon';\n\n` +
    `${imports}\n\n${exportList}\n\n${registry}\n\n` +
    `export type IconName = keyof typeof icons;\n`;
  await writeFile(resolve(outDir, 'index.ts'), index);

  return components.length;
}

async function main(): Promise<void> {
  await mkdir(srcPacks, { recursive: true });
  for (const pack of PACKS) {
    const count = await generatePack(pack);
    console.log(`✓ icons-react: ${pack.name} — ${count} icons`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
