declare module 'vue' {
  export interface GlobalComponents {
    Accordion: (typeof import('uikit-ui'))['Accordion']
    Alert: (typeof import('uikit-ui'))['Alert']
    Aside: (typeof import('uikit-ui'))['Aside']
    Breadcrumbs: (typeof import('uikit-ui'))['Breadcrumb']
    BreadcrumbItem: (typeof import('uikit-ui'))['BreadcrumbItem']
    Button: (typeof import('uikit-ui'))['Button']
    ButtonGroup: (typeof import('uikit-ui'))['ButtonGroup']
    Card: (typeof import('uikit-ui'))['Card']
    // Carousel: (typeof import('uikit-ui'))['Carousel']
    // CarouselItem: (typeof import('uikit-ui'))['CarouselItem']
    Checkbox: (typeof import('uikit-ui'))['Checkbox']
    // Collapse: (typeof import('uikit-ui'))['Collapse']
    // CollapsePanel: (typeof import('uikit-ui'))['CollapsePanel']
    // CollapseTransition: (typeof import('uikit-ui'))['CollapseTransition']
    // DatePicker: (typeof import('uikit-ui'))['DatePicker']
    Divider: (typeof import('uikit-ui'))['Divider']
    // Dropdown: (typeof import('uikit-ui'))['Dropdown']
    // DropdownItem: (typeof import('uikit-ui'))['DropdownItem']
    // DropdownList: (typeof import('uikit-ui'))['DropdownList']
    // Ellipsis: (typeof import('uikit-ui'))['Ellipsis']
    // Form: (typeof import('uikit-ui'))['Form']
    // FormItem: (typeof import('uikit-ui'))['FormItem']
    // FormReset: (typeof import('uikit-ui'))['FormReset']
    // FormSubmit: (typeof import('uikit-ui'))['FormSubmit']
    // Grid: (typeof import('uikit-ui'))['Grid']
    // Highlight: (typeof import('uikit-ui'))['Highlight']
    // Icon: (typeof import('uikit-ui'))['Icon']
    // Input: (typeof import('uikit-ui'))['Input']
    // Mask: (typeof import('uikit-ui'))['Mask']
    // Menu: (typeof import('uikit-ui'))['Menu']
    // MenuGroup: (typeof import('uikit-ui'))['MenuGroup']
    // MenuItem: (typeof import('uikit-ui'))['MenuItem']
    // Modal: (typeof import('uikit-ui'))['Modal']
    // Option: (typeof import('uikit-ui'))['Option']
    // OptionGroup: (typeof import('uikit-ui'))['OptionGroup']
    // Pagination: (typeof import('uikit-ui'))['Pagination']
    // Popper: (typeof import('uikit-ui'))['Popper']
    // Popup: (typeof import('uikit-ui'))['Popup']
    // Progress: (typeof import('uikit-ui'))['Progress']
    // Radio: (typeof import('uikit-ui'))['Radio']
    // RadioGroup: (typeof import('uikit-ui'))['RadioGroup']
    // ResizeObserver: (typeof import('uikit-ui'))['ResizeObserver']
    // Result: (typeof import('uikit-ui'))['Result']
    // Row: (typeof import('uikit-ui'))['Row']
    // Scrollbar: (typeof import('uikit-ui'))['Scrollbar']
    // Select: (typeof import('uikit-ui'))['Select']
    // Skeleton: (typeof import('uikit-ui'))['Skeleton']
    // SkeletonGroup: (typeof import('uikit-ui'))['SkeletonGroup']
    // Switch: (typeof import('uikit-ui'))['Switch']
    // TabNav: (typeof import('uikit-ui'))['TabNav']
    // TabNavItem: (typeof import('uikit-ui'))['TabNavItem']
    // TabPanel: (typeof import('uikit-ui'))['TabPanel']
    // Table: (typeof import('uikit-ui'))['Table']
    // TableColumn: (typeof import('uikit-ui'))['TableColumn']
    // TableColumnGroup: (typeof import('uikit-ui'))['TableColumnGroup']
    // TableSummary: (typeof import('uikit-ui'))['TableSummary']
    // Tabs: (typeof import('uikit-ui'))['Tabs']
    // Tag: (typeof import('uikit-ui'))['Tag']
    // Textarea: (typeof import('uikit-ui'))['Textarea']
    // TimePicker: (typeof import('uikit-ui'))['TimePicker']
    // Tooltip: (typeof import('uikit-ui'))['Tooltip']
    // Tree: (typeof import('uikit-ui'))['Tree']
    // Upload: (typeof import('uikit-ui'))['Upload']
    // VirtualList: (typeof import('uikit-ui'))['VirtualList']
    // Title: (typeof import('uikit-ui'))['Title']
    // Text: (typeof import('uikit-ui'))['Text']
    // Blockquote: (typeof import('uikit-ui'))['Blockquote']
    // OL: (typeof import('uikit-ui'))['OL']
    // UL: (typeof import('uikit-ui'))['UL']
    // H1: (typeof import('uikit-ui'))['H1']
    // H2: (typeof import('uikit-ui'))['H2']
    // H3: (typeof import('uikit-ui'))['H3']
    // H4: (typeof import('uikit-ui'))['H4']
    // H5: (typeof import('uikit-ui'))['H5']
    // H6: (typeof import('uikit-ui'))['H6']
    // P: (typeof import('uikit-ui'))['P']
    // Strong: (typeof import('uikit-ui'))['Strong']
  }

  interface ComponentCustomProperties {
    $confirm: (typeof import('uikit-ui'))['Confirm']
    $contextmenu: (typeof import('uikit-ui'))['Contextmenu']
    $loading: (typeof import('uikit-ui'))['Loading']
    $message: (typeof import('uikit-ui'))['Message']
    $notice: (typeof import('uikit-ui'))['Notice']
    $toast: (typeof import('uikit-ui'))['Toast']
  }
}

export {};
