declare module 'vue' {
  export interface GlobalComponents {
    AcvAccordion: (typeof import('@acronis-platform/ui-component-library'))['AcvAccordion']
    AcvAlert: (typeof import('@acronis-platform/ui-component-library'))['AcvAlert']
    AcvAside: (typeof import('@acronis-platform/ui-component-library'))['AcvAside']
    AcvAutocomplete: (typeof import('@acronis-platform/ui-component-library'))['AcvAutocomplete']
    AcvBreadcrumbs: (typeof import('@acronis-platform/ui-component-library'))['AcvBreadcrumb']
    AcvBreadcrumbItem: (typeof import('@acronis-platform/ui-component-library'))['AcvBreadcrumbItem']
    AcvButton: (typeof import('@acronis-platform/ui-component-library'))['AcvButton']
    AcvButtonGroup: (typeof import('@acronis-platform/ui-component-library'))['AcvButtonGroup']
    AcvCard: (typeof import('@acronis-platform/ui-component-library'))['AcvCard']
    // AcvCarousel: (typeof import('@acronis-platform/ui-component-library'))['AcvCarousel']
    // AcvCarouselItem: (typeof import('@acronis-platform/ui-component-library'))['AcvCarouselItem']
    // AcvCascader: (typeof import('@acronis-platform/ui-component-library'))['AcvCascader']
    AcvCheckbox: (typeof import('@acronis-platform/ui-component-library'))['AcvCheckbox']
    AcvCheckboxButton: (typeof import('@acronis-platform/ui-component-library'))['AcvCheckboxButton']
    AcvCheckboxGroup: (typeof import('@acronis-platform/ui-component-library'))['AcvCheckboxGroup']
    // AcvChip: (typeof import('@acronis-platform/ui-component-library'))['AcvChip']
    // AcvCode: (typeof import('@acronis-platform/ui-component-library'))['AcvCode']
    // AcvCombobox: (typeof import('@acronis-platform/ui-component-library'))['AcvCombobox']
    // AcvContainer: (typeof import('@acronis-platform/ui-component-library'))['AcvContainer']
    // AcvCollapse: (typeof import('@acronis-platform/ui-component-library'))['AcvCollapse']
    // AcvCollapsePanel: (typeof import('@acronis-platform/ui-component-library'))['AcvCollapsePanel']
    // AcvCollapseTransition: (typeof import('@acronis-platform/ui-component-library'))['AcvCollapseTransition']
    // AcvDatePicker: (typeof import('@acronis-platform/ui-component-library'))['AcvDatePicker']
    AcvDivider: (typeof import('@acronis-platform/ui-component-library'))['AcvDivider']
    // AcvDialog: (typeof import('@acronis-platform/ui-component-library'))['AcvDialog']
    // AcvDisclosure: (typeof import('@acronis-platform/ui-component-library'))['AcvDisclosure']
    // AcvDivider: (typeof import('@acronis-platform/ui-component-library'))['AcvDivider']
    // AcvDrawer: (typeof import('@acronis-platform/ui-component-library'))['AcvDrawer']
    // AcvDropdown: (typeof import('@acronis-platform/ui-component-library'))['AcvDropdown']
    // AcvDropdownItem: (typeof import('@acronis-platform/ui-component-library'))['AcvDropdownItem']
    // AcvDropdownList: (typeof import('@acronis-platform/ui-component-library'))['AcvDropdownList']
    // AcvEllipsis: (typeof import('@acronis-platform/ui-component-library'))['AcvEllipsis']
    // AcvForm: (typeof import('@acronis-platform/ui-component-library'))['AcvForm']
    // AcvFormItem: (typeof import('@acronis-platform/ui-component-library'))['AcvFormItem']
    // AcvFormReset: (typeof import('@acronis-platform/ui-component-library'))['AcvFormReset']
    // AcvFormSubmit: (typeof import('@acronis-platform/ui-component-library'))['AcvFormSubmit']
    // AcvGrid: (typeof import('@acronis-platform/ui-component-library'))['AcvGrid']
    // AcvHighlight: (typeof import('@acronis-platform/ui-component-library'))['AcvHighlight']
    // AcvIcon: (typeof import('@acronis-platform/ui-component-library'))['AcvIcon']
    // AcvInput: (typeof import('@acronis-platform/ui-component-library'))['AcvInput']
    AcvList: (typeof import('@acronis-platform/ui-component-library'))['AcvList']
    AcvListItem: (typeof import('@acronis-platform/ui-component-library'))['AcvListItem']
    // AcvMask: (typeof import('@acronis-platform/ui-component-library'))['AcvMask']
    // AcvMenu: (typeof import('@acronis-platform/ui-component-library'))['AcvMenu']
    // AcvMenuGroup: (typeof import('@acronis-platform/ui-component-library'))['AcvMenuGroup']
    // AcvMenuItem: (typeof import('@acronis-platform/ui-component-library'))['AcvMenuItem']
    // AcvModal: (typeof import('@acronis-platform/ui-component-library'))['AcvModal']
    // AcvOption: (typeof import('@acronis-platform/ui-component-library'))['AcvOption']
    // AcvOptionGroup: (typeof import('@acronis-platform/ui-component-library'))['AcvOptionGroup']
    // AcvPagination: (typeof import('@acronis-platform/ui-component-library'))['AcvPagination']
    AcvPopper: (typeof import('@acronis-platform/ui-component-library'))['AcvPopper']
    AcvPopover: (typeof import('@acronis-platform/ui-component-library'))['AcvPopover']
    // AcvPopup: (typeof import('@acronis-platform/ui-component-library'))['AcvPopup']
    // AcvProgress: (typeof import('@acronis-platform/ui-component-library'))['AcvProgress']
    // AcvRadio: (typeof import('@acronis-platform/ui-component-library'))['AcvRadio']
    // AcvRadioGroup: (typeof import('@acronis-platform/ui-component-library'))['AcvRadioGroup']
    // AcvResizeObserver: (typeof import('@acronis-platform/ui-component-library'))['AcvResizeObserver']
    // AcvResult: (typeof import('@acronis-platform/ui-component-library'))['AcvResult']
    // AcvRow: (typeof import('@acronis-platform/ui-component-library'))['AcvRow']
    // AcvScrollbar: (typeof import('@acronis-platform/ui-component-library'))['AcvScrollbar']
    // AcvStepper: (typeof import('@acronis-platform/ui-component-library'))['AcvStepper']
    // AcvSelect: (typeof import('@acronis-platform/ui-component-library'))['AcvSelect']
    // AcvSkeleton: (typeof import('@acronis-platform/ui-component-library'))['AcvSkeleton']
    // AcvSkeletonGroup: (typeof import('@acronis-platform/ui-component-library'))['AcvSkeletonGroup']
    AcvSwitch: (typeof import('@acronis-platform/ui-component-library'))['AcvSwitch']
    // AcvTabNav: (typeof import('@acronis-platform/ui-component-library'))['AcvTabNav']
    // AcvTabNavItem: (typeof import('@acronis-platform/ui-component-library'))['AcvTabNavItem']
    // AcvTabPanel: (typeof import('@acronis-platform/ui-component-library'))['AcvTabPanel']
    // AcvTable: (typeof import('@acronis-platform/ui-component-library'))['AcvTable']
    // AcvTableColumn: (typeof import('@acronis-platform/ui-component-library'))['AcvTableColumn']
    // AcvTableColumnGroup: (typeof import('@acronis-platform/ui-component-library'))['AcvTableColumnGroup']
    // AcvTableSummary: (typeof import('@acronis-platform/ui-component-library'))['AcvTableSummary']
    // AcvTabs: (typeof import('@acronis-platform/ui-component-library'))['AcvTabs']
    // AcvTag: (typeof import('@acronis-platform/ui-component-library'))['AcvTag']
    // AcvTextarea: (typeof import('@acronis-platform/ui-component-library'))['AcvTextarea']
    // AcvTiles: (typeof import('@acronis-platform/ui-component-library'))['AcvTiles']
    // AcvTimePicker: (typeof import('@acronis-platform/ui-component-library'))['AcvTimePicker']
    AcvToolbar: (typeof import('@acronis-platform/ui-component-library'))['AcvToolbar']
    AcvTooltip: (typeof import('@acronis-platform/ui-component-library'))['AcvTooltip']
    // AcvTree: (typeof import('@acronis-platform/ui-component-library'))['AcvTree']
    // AcvUpload: (typeof import('@acronis-platform/ui-component-library'))['AcvUpload']
    // AcvVirtualList: (typeof import('@acronis-platform/ui-component-library'))['AcvVirtualList']
    AcvTypography: (typeof import('@acronis-platform/ui-component-library'))['AcvTypography']
    // AcvTitle: (typeof import('@acronis-platform/ui-component-library'))['AcvTitle']
    // AcvText: (typeof import('@acronis-platform/ui-component-library'))['AcvText']
    // AcvBlockquote: (typeof import('@acronis-platform/ui-component-library'))['AcvBlockquote']
    // AcvOL: (typeof import('@acronis-platform/ui-component-library'))['AcvOL']
    // AcvUL: (typeof import('@acronis-platform/ui-component-library'))['AcvUL']
    // AcvH1: (typeof import('@acronis-platform/ui-component-library'))['AcvH1']
    // AcvH2: (typeof import('@acronis-platform/ui-component-library'))['AcvH2']
    // AcvH3: (typeof import('@acronis-platform/ui-component-library'))['AcvH3']
    // AcvH4: (typeof import('@acronis-platform/ui-component-library'))['AcvH4']
    // AcvH5: (typeof import('@acronis-platform/ui-component-library'))['AcvH5']
    // AcvH6: (typeof import('@acronis-platform/ui-component-library'))['AcvH6']
    // AcvP: (typeof import('@acronis-platform/ui-component-library'))['AcvP']
    // AcvStrong: (typeof import('@acronis-platform/ui-component-library'))['AcvStrong']
  }

  interface ComponentCustomProperties {
    $confirm: (typeof import('@acronis-platform/ui-component-library'))['AcvConfirm']
    $contextmenu: (typeof import('@acronis-platform/ui-component-library'))['AcvContextmenu']
    $loading: (typeof import('@acronis-platform/ui-component-library'))['AcvLoading']
    $message: (typeof import('@acronis-platform/ui-component-library'))['AcvMessage']
    $notice: (typeof import('@acronis-platform/ui-component-library'))['AcvNotice']
    $toast: (typeof import('@acronis-platform/ui-component-library'))['AcvToast']
  }
}

export {};
