export {
  Table,
  tableVariants,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
  type TableProps,
  type TableHeaderProps,
  type TableFooterProps,
  type TableRowProps,
  type TableHeadProps,
  type TableCellProps,
  type TableBorders,
  type TableBorderValue,
  type TableBorderStrength,
  type TableColumnPin,
} from './table';
