import { directives } from './directives.ts';

// eslint-disable-next-line node/prefer-global/process
const isProd = process.env.NODE_ENV === 'production';

const componentsList = [
  { text: 'Accordion', link: '/components/accordion/accordion.doc' },
  { text: 'Alert', link: '/components/alert/alert.doc' },
  { text: 'Autocomplete', link: '/components/autocomplete/autocomplete.doc' },
  { text: 'BaseInput', link: '/components/baseInput/baseInput.doc' },
  { text: 'Breadcrumbs', link: '/components/breadcrumbs/breadcrumbs.doc' },
  { text: 'Button', link: '/components/button/button.doc', readyForProduction: true },
  { text: 'ButtonGroup', link: '/components/button-group/buttonGroup.doc' },
  { text: 'Card', link: '/components/card/card.doc' },
  { text: 'Carousel', link: '/components/carousel/carousel.doc' },
  { text: 'Cascader', link: '/components/cascader/cascader.doc' },
  { text: 'Checkbox', link: '/components/checkbox/checkbox.doc' },
  { text: 'CheckboxButton', link: '/components/checkboxButton/checkboxButton.doc' },
  { text: 'CheckboxGroup', link: '/components/checkboxGroup/checkboxGroup.doc' },
  { text: 'Chip', link: '/components/chip/chip.doc' },
  { text: 'Code', link: '/components/code/code.doc' },
  { text: 'Column', link: '/components/column/column.doc' },
  { text: 'Combobox', link: '/components/combobox/combobox.doc' },
  { text: 'ConfigProvider', link: '/components/configProvider/configProvider.doc' },
  { text: 'ConfirmDialog', link: '/components/confirmDialog/confirmDialog.doc' },
  { text: 'Container', link: '/components/container/container.doc' },
  { text: 'Data Table', link: '/components/table/table.doc' },
  { text: 'DatePicker', link: '/components/datePicker/datePicker.doc' },
  { text: 'Dialog', link: '/components/dialog/dialog.doc' },
  { text: 'Disclosure', link: '/components/disclosure/disclosure.doc' },
  { text: 'Divider', link: '/components/divider/divider.doc' },
  { text: 'Drawer', link: '/components/drawer/drawer.doc' },
  { text: 'Dropdown', link: '/components/dropdown/dropdown.doc' },
  { text: 'FileBrowser', link: '/components/fileBrowser/fileBrowser.doc' },
  { text: 'FilePicker', link: '/components/filePicker/filePicker.doc' },
  { text: 'FileUpload', link: '/components/fileUpload/fileUpload.doc' },
  { text: 'Filter', link: '/components/filter/filter.doc' },
  { text: 'FittedActions', link: '/components/fitted-actions/fittedActions.doc' },
  { text: 'FlowChart', link: '/components/flowChart/flowChart.doc' },
  { text: 'Footer', link: '/components/footer/footer.doc' },
  { text: 'Form', link: '/components/form/form.doc' },
  { text: 'FormDialog', link: '/components/formDialog/formDialog.doc' },
  { text: 'FormError', link: '/components/formError/formError.doc' },
  { text: 'FormItem', link: '/components/formItem/formItem.doc' },
  { text: 'Grid', link: '/components/grid/grid.doc' },
  { text: 'Header', link: '/components/header/header.doc' },
  { text: 'Icon', link: '/components/icon/icon.doc' },
  { text: 'IconButton', link: '/components/icon-button/iconButton.doc' },
  { text: 'InfiniteScroll', link: '/components/infiniteScroll/infiniteScroll.doc' },
  { text: 'Input', link: '/components/input/input' },
  { text: 'InputNumber', link: '/components/inputNumber/inputNumber.doc' },
  { text: 'Link', link: '/components/link/link.doc' },
  { text: 'List', link: '/components/list/list.doc' },
  { text: 'Loading', link: '/components/loading/loading.doc' },
  { text: 'Main', link: '/components/main/main.doc' },
  { text: 'Map', link: '/components/map/map.doc' },
  { text: 'Markup Table', link: '/components/markup-table/markupTable.doc' },
  { text: 'Menu', link: '/components/menu/menu.doc' },
  { text: 'MenuGroup', link: '/components/menuGroup/menuGroup.doc' },
  { text: 'MenuItem', link: '/components/menuItem/menuItem.doc' },
  { text: 'Modal', link: '/components/modal/modal.doc' },
  { text: 'Notification', link: '/components/notification.doc' },
  { text: 'NumPicker', link: '/components/numPicker/numPicker.doc' },
  { text: 'Option', link: '/components/option/option.doc' },
  { text: 'OptionGroup', link: '/components/optionGroup/optionGroup.doc' },
  { text: 'Pagination', link: '/components/pagination/pagination.doc' },
  { text: 'Password', link: '/components/password/password.doc' },
  { text: 'PieChart', link: '/components/pie-chart/pieChart.doc' },
  { text: 'Popover', link: '/components/popover/popover.doc' },
  { text: 'Popper', link: '/components/popper/popper.doc' },
  { text: 'Progress', link: '/components/progress/progress.doc' },
  { text: 'Radio', link: '/components/radio/radio.doc' },
  { text: 'RadioButton', link: '/components/radioButton/radioButton.doc' },
  { text: 'RadioGroup', link: '/components/radioGroup/radioGroup.doc' },
  { text: 'Ribbon', link: '/components/ribbon/ribbon.doc' },
  { text: 'Row', link: '/components/row/row.doc' },
  { text: 'ScriptEditor', link: '/components/scriptEditor/scriptEditor.doc' },
  { text: 'Search', link: '/components/search/search.doc' },
  { text: 'Select', link: '/components/select/select.doc' },
  { text: 'Skeleton', link: '/components/skeleton/skeleton.doc' },
  { text: 'Slider', link: '/components/slider/slider.doc' },
  { text: 'Spinner', link: '/components/spinner/spinner.doc' },
  { text: 'SplitButton', link: '/components/splitButton/splitButton.doc' },
  { text: 'Stepper', link: '/components/stepper/stepper.doc' },
  { text: 'StepperItem', link: '/components/stepperItem/stepperItem.doc' },
  { text: 'Submenu', link: '/components/submenu/submenu.doc' },
  { text: 'Switch', link: '/components/switch/switch.doc' },
  { text: 'TableColumn', link: '/components/tableColumn/tableColumn.doc' },
  { text: 'Tabs', link: '/components/tabs/tabs.doc' },
  { text: 'Tag', link: '/components/tag/tag.doc' },
  { text: 'TextArea', link: '/components/textarea/textarea.doc' },
  { text: 'ThemeProvider', link: '/components/themeProvider/themeProvider.doc' },
  { text: 'Tiles', link: '/components/tiles/tiles.doc' },
  { text: 'TimePicker', link: '/components/timePicker/timePicker.doc' },
  { text: 'Toolbar', link: '/components/toolbar/toolbar.doc' },
  { text: 'Tooltip', link: '/components/tooltip/tooltip.doc' },
  { text: 'Tree', link: '/components/tree/tree.doc' },
  { text: 'Typography', link: '/components/typography/typography.doc' },
  { text: 'Upload', link: '/components/upload/upload.doc' },
  { text: 'Virtual Scroll', link: '/components/virtual-scroll/virtualScroll.doc' },
  {
    text: 'Directives',
    items: directives,
  }
];

export const enComponents = [
  ...componentsList.filter(c => (isProd && c.readyForProduction) || !isProd),
];
