import '../themes/acronis/src/index.scss';

import Alert from '../packages/alert/index.js';
// import Aside from '../packages/aside/index.js';
// import Autocomplete from '../packages/autocomplete/index.js';
// import Breadcrumb from '../packages/breadcrumb/index.js';
// import BreadcrumbItem from '../packages/breadcrumb-item/index.js';
import Button from '../packages/button/index.js';
import Card from '../packages/card/index.js';
// import Carousel from '../packages/carousel/index.js';
// import CarouselItem from '../packages/carousel-item/index.js';
// import Cascader from '../packages/cascader/index.js';
import Checkbox from '../packages/checkbox/index.js';
import CheckboxButton from '../packages/checkbox-button/index.js';
import CheckboxGroup from '../packages/checkbox-group/index.js';
import Chip from '../packages/chip/index.js';
// import Col from '../packages/col/index.js';
// import Collapse from '../packages/collapse/index.js';
// import CollapseItem from '../packages/collapse-item/index.js';
// import Combobox from '../packages/combobox/index.js';
// import Container from '../packages/container/index.js';
// import DatePicker from '../packages/date-picker/index.js';
import Dialog from '../packages/dialog/index.js';
// import Divider from '../packages/divider/index.js';
// import Dropdown from '../packages/dropdown/index.js';
// import DropdownItem from '../packages/dropdown-item/index.js';
// import DropdownMenu from '../packages/dropdown-menu/index.js';
// import FileBrowser from '../packages/file-browser/index.js';
// import FilePicker from '../packages/file-picker/index.js';
// import Filter from '../packages/filter/index.js';
// import Footer from '../packages/footer/index.js';
import Form from '../packages/form/index.js';
import FormError from '../packages/form-error/index.js';
import FormItem from '../packages/form-item/index.js';
// import Highlight from '../packages/highlight';
import Icon from '../packages/icon/index.js';
import Input from '../packages/input/index.js';
import Link from '../packages/link/index.js';
// import Loading from '../packages/loading/index.js';
// import Main from '../packages/main/index.js';
// import Map from '../packages/map/index.js';
// import Menu from '../packages/menu/index.js';
// import MenuGroup from '../packages/menu-group/index.js';
// import MenuItem from '../packages/menu-item/index.js';
// import Notification from '../packages/notification/index.js';
// import NotificationComponent from '../packages/notification-component/index.js';
import NumPicker from '../packages/num-picker/index.js';
// import Option from '../packages/option/index.js';
// import OptionGroup from '../packages/option-group/index.js';
// import Pagination from '../packages/pagination/index.js';
import Password from '../packages/password/index.js';
// import Popover from '../packages/popover/index.js';
// import Progress from '../packages/progress/index.js';
import Radio from '../packages/radio/index.js';
import RadioButton from '../packages/radio-button/index.js';
import RadioGroup from '../packages/radio-group/index.js';
// import Row from '../packages/row/index.js';
// import ScriptEditor from '../packages/script-editor/index.js';
// import Scrollbar from '../packages/scrollbar/index.js';
// import Search from '../packages/search/index.js';
// import Select from '../packages/select/index.js';
// import Slider from '../packages/slider/index.js';
// import Spinner from '../packages/spinner/index.js';
// import SplitButton from '../packages/split-button/index.js';
// import Step from '../packages/step/index.js';
// import Stepper from '../packages/stepper/index.js';
// import StepperItem from '../packages/stepper-item/index.js';
// import Steps from '../packages/steps/index.js';
// import Submenu from '../packages/submenu/index.js';
import Switch from '../packages/switch/index.js';
// import TabNav from '../packages/tab-nav';
// import TabPane from '../packages/tab-pane';
// import TableActionsColumn from '../packages/table-actions-column/index.js';
// import TableActions from '../packages/table-actions/index.js';
// import TableColumn from '../packages/table-column/index.js';
// import TableColumnsVisibility from '../packages/table-columns-visibility/index.js';
// import TableDataCell from '../packages/table-data-cell/index.js';
// import TableRowsGroup from '../packages/table-rows-group/index.js';
// import Table from '../packages/table/index.js';
// import Tabs from '../packages/tabs/index.js';
// import Tag from '../packages/tag/index.js';
// import TextMiddleEllipsis from '../packages/text-middle-ellipsis';
// import TimePicker from '../packages/time-picker/index.js';
import Tooltip from '../packages/tooltip/index.js';
// import Tree from '../packages/tree/index.js';
// import Upload from '../packages/upload/index.js';

// import AboutWindow from '../packages/widgets/about/index.js';
// import AlertWidget from '../packages/widgets/alert/index.js';
// import DetailsTable from '../packages/widgets/details-table/index.js';
// import DetailsView from '../packages/widgets/details-view/index.js';
// import Details from '../packages/widgets/details/index.js';
// import FittedActions from '../packages/widgets/fitted-actions/index.js';
// import HeaderMenu from '../packages/widgets/header-menu/index.js';
// import HeaderSearch from '../packages/widgets/header-search/index.js';
// import Header from '../packages/widgets/header/index.js';
// import LineChart from '../packages/widgets/line-chart/index.js';
// import LiveTracker from '../packages/widgets/live-tracker/index.js';
// import LoadingComplex from '../packages/widgets/loading-complex/index.js';
// import MultiSearch from '../packages/widgets/multi-search/index.js';
// import PieChart from '../packages/widgets/pie-chart/index.js';
// import PopoverWidget from '../packages/widgets/popover-widget/index.js';
// import ProgressRadial from '../packages/widgets/progress-radial/index.js';
// import SidebarAction from '../packages/widgets/sidebar/sidebar-action/index.js';
// import SidebarLayout from '../packages/widgets/sidebar/sidebar-layout/index.js';
// import SidebarPanel from '../packages/widgets/sidebar/sidebar-panel/index.js';
// import SidebarTitle from '../packages/widgets/sidebar/sidebar-title/index.js';
// import StackedAreaChart from '../packages/widgets/stacked-area-chart/index.js';
// import TableWidget from '../packages/widgets/table-widget/index.js';
// import ToolbarContainer from '../packages/widgets/toolbar-container/index.js';
// import ToolbarSearch from '../packages/widgets/toolbar-search/index.js';
// import Toolbar from '../packages/widgets/toolbar/index.js';
// import WhatIsNew from '../packages/widgets/what-is-new/index.js';
// import WidgetWrapper from '../packages/widgets/widget-wrapper/index.js';

// export const ElAboutWindow = AboutWindow;
export const ElAlert = Alert;
// export const ElAlertWidget = AlertWidget;
// export const ElAside = Aside;
// export const ElAutocomplete = Autocomplete;
// export const ElBreadcrumb = Breadcrumb;
// export const ElBreadcrumbItem = BreadcrumbItem;
export const ElButton = Button;
export const ElCard = Card;
// export const ElCarousel = Carousel;
// export const ElCarouselItem = CarouselItem;
// export const ElCascader = Cascader;
export const ElCheckbox = Checkbox;
export const ElCheckboxButton = CheckboxButton;
export const ElCheckboxGroup = CheckboxGroup;
export const ElChip = Chip;
// export const ElCol = Col;
// export const ElCollapse = Collapse;
// export const ElCollapseItem = CollapseItem;
// export const ElCombobox = Combobox;
// export const ElContainer = Container;
// export const ElDatePicker = DatePicker;
// export const ElDetails = Details;
// export const ElDetailsTable = DetailsTable;
// export const ElDetailsView = DetailsView;
export const ElDialog = Dialog;
// export const ElDivider = Divider;
// export const ElDropdown = Dropdown;
// export const ElDropdownItem = DropdownItem;
// export const ElDropdownMenu = DropdownMenu;
// export const ElFileBrowser = FileBrowser;
// export const ElFilePicker = FilePicker;
// export const ElFilter = Filter;
// export const ElFittedActions = FittedActions;
// export const ElFooter = Footer;
export const ElForm = Form;
export const ElFormError = FormError;
export const ElFormItem = FormItem;
// export const ElHeader = Header;
// export const ElHeaderMenu = HeaderMenu;
// export const ElHeaderSearch = HeaderSearch;
// export const ElHighlight = Highlight;
export const ElIcon = Icon;
export const ElInput = Input;
// export const ElLineChart = LineChart;
export const ElLink = Link;
// export const ElLiveTracker = LiveTracker;
// export const ElLoading = Loading;
// export const ElLoadingComplex = LoadingComplex;
// export const ElMain = Main;
// export const ElMap = Map;
// export const ElMenu = Menu;
// export const ElMenuGroup = MenuGroup;
// export const ElMenuItem = MenuItem;
// export const ElMultiSearch = MultiSearch;
// export const ElNotification = Notification;
// export const ElNotificationComponent = NotificationComponent;
export const ElNumPicker = NumPicker;
// export const ElOption = Option;
// export const ElOptionGroup = OptionGroup;
// export const ElPagination = Pagination;
export const ElPassword = Password;
// export const ElPieChart = PieChart;
// export const ElPopover = Popover;
// export const ElPopoverWidget = PopoverWidget;
// export const ElProgress = Progress;
// export const ElProgressRadial = ProgressRadial;
export const ElRadio = Radio;
export const ElRadioButton = RadioButton;
export const ElRadioGroup = RadioGroup;
// export const ElRow = Row;
// export const ElScriptEditor = ScriptEditor;
// export const ElScrollbar = Scrollbar;
// export const ElSearch = Search;
// export const ElSelect = Select;
// export const ElSidebarAction = SidebarAction;
// export const ElSidebarLayout = SidebarLayout;
// export const ElSidebarPanel = SidebarPanel;
// export const ElSidebarTitle = SidebarTitle;
// export const ElSlider = Slider;
// export const ElSpinner = Spinner;
// export const ElSplitButton = SplitButton;
// export const ElStackedAreaChart = StackedAreaChart;
// export const ElStep = Step;
// export const ElStepper = Stepper;
// export const ElStepperItem = StepperItem;
// export const ElSteps = Steps;
// export const ElSubmenu = Submenu;
export const ElSwitch = Switch;
// export const ElTable = Table;
// export const ElTableActions = TableActions;
// export const ElTableActionsColumn = TableActionsColumn;
// export const ElTableColumn = TableColumn;
// export const ElTableColumnsVisibility = TableColumnsVisibility;
// export const ElTableDataCell = TableDataCell;
// export const ElTableRowsGroup = TableRowsGroup;
// export const ElTableWidget = TableWidget;
// export const ElTabNav = TabNav;
// export const ElTabPane = TabPane;
// export const ElTabs = Tabs;
// export const ElTag = Tag;
// export const ElTextMiddleEllipsis = TextMiddleEllipsis;
// export const ElTimePicker = TimePicker;
// export const ElToolbar = Toolbar;
// export const ElToolbarContainer = ToolbarContainer;
// export const ElToolbarSearch = ToolbarSearch
export const ElTooltip = Tooltip;
// export const ElTree = Tree;
// export const ElUpload = Upload;
// export const ElWhatIsNew = WhatIsNew;
// export const ElWidgetWrapper = WidgetWrapper;