// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: Avatar
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "textColor": {
        "avatar-global-text": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "avatar-label-orange": "light-dark(rgb(153 69 0), rgb(255 222 194))",
        "avatar-label-red": "light-dark(rgb(152 27 27), rgb(251 218 218))",
        "avatar-label-teal": "light-dark(rgb(4 73 67), rgb(209 240 237))",
        "avatar-label-violet": "light-dark(rgb(130 23 130), rgb(250 209 250))",
        "avatar-label-yellow": "light-dark(rgb(138 99 0), rgb(255 238 178))"
      },
      "borderColor": {
        "avatar-global-avatar-border": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "fontFamily": {
        "avatar-global-label-text-style": "Inter, system-ui, sans-serif",
        "avatar-global-text-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "avatar-global-label-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "avatar-global-text-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "avatar-global-avatar-border-border-width": "2px",
        "avatar-global-avatar-group-gap": "-6px",
        "avatar-global-avatar-size": "32px",
        "avatar-global-container-gap": "8px"
      },
      "borderRadius": {
        "avatar-global-avatar-border-radius": "999px"
      }
    },
  },
};
