// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: Breadcrumb
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "textColor": {
        "breadcrumb-link-label-active": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "breadcrumb-link-label-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "breadcrumb-link-label-idle": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "breadcrumb-page-label": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "fill": {
        "breadcrumb-separator-icon": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fontFamily": {
        "breadcrumb-link-label-text-style": "Inter, system-ui, sans-serif",
        "breadcrumb-page-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "breadcrumb-link-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "breadcrumb-page-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "breadcrumb-separator-icon-size": "16px",
        "breadcrumb-list-gap": "4px"
      }
    },
  },
};
