// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: ButtonIcon
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-icon-global-container-active": "light-dark(rgb(216 222 228), rgb(216 222 228))",
        "button-icon-global-container-disabled": "light-dark(transparent, transparent)",
        "button-icon-global-container-hover": "light-dark(rgb(236 238 239), rgb(236 238 239))",
        "button-icon-global-container-idle": "light-dark(transparent, transparent)"
      },
      "borderColor": {
        "button-icon-secondary-container-border-color-active": "light-dark(transparent, transparent)",
        "button-icon-secondary-container-border-color-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "button-icon-secondary-container-border-color-hover": "light-dark(transparent, transparent)",
        "button-icon-secondary-container-border-color-idle": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fill": {
        "button-icon-global-icon-active": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "button-icon-global-icon-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "button-icon-global-icon-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "button-icon-global-icon-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "spacing": {
        "button-icon-global-container-height": "32px",
        "button-icon-global-container-padding-x": "4px",
        "button-icon-global-icon-size": "24px",
        "button-icon-secondary-container-border-width": "1px"
      },
      "borderRadius": {
        "button-icon-global-container-border-radius": "4px"
      }
    },
  },
};
