// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: CardFilter
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "card-filter-global-container-active": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "card-filter-global-container-hover": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "card-filter-global-container-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "card-filter-global-label": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "card-filter-clickable-value": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "card-filter-static-value-disabled": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "card-filter-static-value-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "borderColor": {
        "card-filter-global-border-color-active": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "card-filter-global-border-color-focused": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "card-filter-global-border-color-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "card-filter-global-border-color-idle": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fontFamily": {
        "card-filter-global-label-text-style": "Inter, system-ui, sans-serif",
        "card-filter-global-value-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "card-filter-global-label-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "card-filter-global-value-text-style": [
          "24px",
          {
            "lineHeight": "32px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "card-filter-global-container-border-width": "1px",
        "card-filter-global-container-height": "64px",
        "card-filter-global-container-padding-x": "16px",
        "card-filter-global-container-padding-y": "8px",
        "card-filter-global-content-gap": "8px"
      },
      "borderRadius": {
        "card-filter-global-container-border-radius": "8px"
      }
    },
  },
};
