// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: Chips
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "chips-container-active": "light-dark(rgb(216 222 228), rgb(216 222 228))",
        "chips-container-hover": "light-dark(rgb(236 238 239), rgb(236 238 239))",
        "chips-container-idle": "light-dark(rgb(246 246 247), rgb(246 246 247))"
      },
      "textColor": {
        "chips-label": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "borderColor": {
        "chips-border-active": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "chips-border-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "chips-border-idle": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fill": {
        "chips-icon": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "fontFamily": {
        "chips-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "chips-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "chips-border-width": "1px",
        "chips-container-gap": "4px",
        "chips-container-height": "24px",
        "chips-container-padding-x": "8px",
        "chips-container-width-min": "48px",
        "chips-icon-size": "16px"
      },
      "borderRadius": {
        "chips-border-radius": "12px"
      }
    },
  },
};
