// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: InputTextArea
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "input-text-area-box-disabled": "light-dark(rgb(246 246 247), rgb(246 246 247))",
        "input-text-area-box-hover": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "input-text-area-box-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "input-text-area-description-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-text-area-description-hover": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-text-area-description-idle": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-text-area-error-msg-error": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-text-area-label-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-text-area-label-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-text-area-label-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-text-area-placeholder-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-text-area-placeholder-hover": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-text-area-placeholder-idle": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-text-area-required": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-text-area-value-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-text-area-value-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-text-area-value-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "borderColor": {
        "input-text-area-border-color-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "input-text-area-border-color-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-text-area-border-color-idle": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "input-text-area-error-msg-box-border-color-hover": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-text-area-error-msg-box-border-color-idle": "light-dark(rgb(226 54 54), rgb(229 77 77))"
      },
      "ringColor": {
        "input-text-area-border-color-focus": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "fontFamily": {
        "input-text-area-description-text-style": "Inter, system-ui, sans-serif",
        "input-text-area-error-msg-error-text-style": "Inter, system-ui, sans-serif",
        "input-text-area-label-text-style": "Inter, system-ui, sans-serif",
        "input-text-area-placeholder-text-style": "Inter, system-ui, sans-serif",
        "input-text-area-required-text-style": "Inter, system-ui, sans-serif",
        "input-text-area-value-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "input-text-area-description-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-text-area-error-msg-error-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-text-area-label-text-style": [
          "14px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-text-area-placeholder-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-text-area-required-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-text-area-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "input-text-area-box-border-width": "1px",
        "input-text-area-box-gap": "12px",
        "input-text-area-box-height-min": "96px",
        "input-text-area-box-padding-x": "12px",
        "input-text-area-box-padding-y": "8px",
        "input-text-area-container-gap": "4px",
        "input-text-area-container-width-min": "256px",
        "input-text-area-container-label-gap": "4px"
      },
      "borderRadius": {
        "input-text-area-box-border-radius": "4px"
      }
    },
  },
};
