// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: InputSelect
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "input-select-dropdown-container": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "input-select-dropdown-item-selected-container-disabled": "light-dark(rgb(246 246 247), rgb(246 246 247))",
        "input-select-dropdown-item-selected-container-hover": "light-dark(rgb(216 222 228), rgb(216 222 228))",
        "input-select-dropdown-item-selected-container-idle": "light-dark(rgb(216 222 228), rgb(216 222 228))",
        "input-select-dropdown-item-unselected-container-disabled": "light-dark(rgb(246 246 247), rgb(246 246 247))",
        "input-select-dropdown-item-unselected-container-hover": "light-dark(rgb(236 238 239), rgb(236 238 239))",
        "input-select-dropdown-item-unselected-container-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "input-select-global-box-disabled": "light-dark(rgb(246 246 247), rgb(246 246 247))",
        "input-select-global-box-hover": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "input-select-global-box-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "input-select-dropdown-dropdown-search-label-placeholder": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-select-dropdown-dropdown-search-label-value": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-select-dropdown-item-global-label": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-select-global-label-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-select-global-label-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-select-global-label-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-select-global-placeholder-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-select-global-placeholder-hover": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-select-global-placeholder-idle": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-select-global-required": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-select-global-value-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-select-global-value-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-select-global-value-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-select-error-error-msg": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-select-error-icon-expand-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "input-select-error-icon-expand-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-select-error-icon-expand-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-select-normal-description-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-select-normal-description-hover": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-select-normal-description-idle": "light-dark(rgb(54 65 74), rgb(54 65 74))"
      },
      "borderColor": {
        "input-select-dropdown-container-border-color": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "input-select-dropdown-section-container-border-color": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "input-select-error-box-border-color-hover": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-select-error-box-border-color-idle": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-select-normal-box-border-color-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "input-select-normal-box-border-color-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-select-normal-box-border-color-idle": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fill": {
        "input-select-error-icon-hover": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-select-error-icon-idle": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-select-normal-icon-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-select-normal-icon-hover": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-select-normal-icon-idle": "light-dark(rgb(54 65 74), rgb(54 65 74))"
      },
      "fontFamily": {
        "input-select-dropdown-dropdown-search-label-text-style": "Inter, system-ui, sans-serif",
        "input-select-dropdown-section-label-group-text-style": "Inter, system-ui, sans-serif",
        "input-select-global-label-text-style": "Inter, system-ui, sans-serif",
        "input-select-global-required-text-style": "Inter, system-ui, sans-serif",
        "input-select-global-value-text-style": "Inter, system-ui, sans-serif",
        "input-select-error-error-msg-text-style": "Inter, system-ui, sans-serif",
        "input-select-normal-description-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "input-select-dropdown-dropdown-search-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-select-dropdown-section-label-group-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "input-select-global-label-text-style": [
          "14px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-select-global-required-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-select-global-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-select-error-error-msg-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-select-normal-description-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "input-select-dropdown-dropdown-search-gap": "8px",
        "input-select-dropdown-dropdown-search-padding-x": "12px",
        "input-select-dropdown-dropdown-search-padding-y": "12px",
        "input-select-dropdown-container-border-width": "1px",
        "input-select-dropdown-container-gap": "0px",
        "input-select-dropdown-container-padding-x": "0px",
        "input-select-dropdown-container-padding-y": "0px",
        "input-select-dropdown-container-status-gap": "8px",
        "input-select-dropdown-container-status-padding-x": "16px",
        "input-select-dropdown-container-status-padding-y": "16px",
        "input-select-dropdown-container-status-width-min": "128px",
        "input-select-dropdown-item-global-container-gap": "8px",
        "input-select-dropdown-item-global-container-height": "40px",
        "input-select-dropdown-item-global-container-padding-x": "12px",
        "input-select-dropdown-item-global-container-padding-y": "8px",
        "input-select-dropdown-section-container-border-width": "1px",
        "input-select-dropdown-section-container-padding-y": "0px",
        "input-select-dropdown-section-container-header-padding-x": "12px",
        "input-select-dropdown-section-container-header-padding-y": "8px",
        "input-select-dropdown-section-list-gap": "0px",
        "input-select-global-box-border-width": "1px",
        "input-select-global-box-gap": "12px",
        "input-select-global-box-height": "32px",
        "input-select-global-box-padding-x": "12px",
        "input-select-global-box-padding-y": "4px",
        "input-select-global-container-gap": "4px",
        "input-select-global-container-width-min": "128px",
        "input-select-global-container-label-gap": "4px"
      },
      "borderRadius": {
        "input-select-dropdown-container-border-radius": "4px",
        "input-select-global-box-border-radius": "4px"
      }
    },
  },
};
