// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: InputSearch
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "input-search-box-disabled": "light-dark(rgb(246 246 247), rgb(246 246 247))",
        "input-search-box-hover": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "input-search-box-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "input-search-placeholder-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-search-placeholder-hover": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-search-placeholder-idle": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "input-search-required": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-search-value-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "input-search-value-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-search-value-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "borderColor": {
        "input-search-border-color-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "input-search-border-color-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-search-border-color-idle": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fill": {
        "input-search-clear-icon": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-search-icon-search-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "input-search-icon-search-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "input-search-icon-search-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "fontFamily": {
        "input-search-label-text-style": "Inter, system-ui, sans-serif",
        "input-search-required-text-style": "Inter, system-ui, sans-serif",
        "input-search-value-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "input-search-label-text-style": [
          "14px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-search-required-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-search-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "input-search-box-border-width": "1px",
        "input-search-box-gap": "8px",
        "input-search-box-height": "32px",
        "input-search-box-padding-x": "12px",
        "input-search-box-padding-y": "4px",
        "input-search-container-gap": "4px",
        "input-search-container-width-min": "128px",
        "input-search-container-label-gap": "4px"
      },
      "borderRadius": {
        "input-search-box-border-radius": "4px"
      }
    },
  },
};
