// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: Link
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "fill": {
        "link-external-icon-active": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "link-external-icon-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "link-external-icon-hover": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "link-external-icon-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "fontFamily": {
        "link-text-style-active": "Inter, system-ui, sans-serif",
        "link-text-style-disabled": "Inter, system-ui, sans-serif",
        "link-text-style-hover": "Inter, system-ui, sans-serif",
        "link-text-style-idle": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "link-text-style-active": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-text-style-disabled": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-text-style-hover": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "link-text-style-idle": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "link-container-gap": "4px",
        "link-container-height": "32px"
      }
    },
  },
};
