// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: Radio
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "radio-checked-box-active": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "radio-checked-box-disabled": "light-dark(rgb(246 246 247), rgb(246 246 247))",
        "radio-checked-box-hover": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "radio-checked-box-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "radio-unchecked-box-active": "light-dark(rgb(216 222 228), rgb(216 222 228))",
        "radio-unchecked-box-disabled": "light-dark(rgb(246 246 247), rgb(246 246 247))",
        "radio-unchecked-box-hover": "light-dark(rgb(236 238 239), rgb(236 238 239))",
        "radio-unchecked-box-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "radio-global-description": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "radio-global-label": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "borderColor": {
        "radio-checked-box-border-color-active": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "radio-checked-box-border-color-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "radio-checked-box-border-color-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "radio-checked-box-border-color-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "radio-unchecked-box-border-color-active": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "radio-unchecked-box-border-color-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "radio-unchecked-box-border-color-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "radio-unchecked-box-border-color-idle": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fill": {
        "radio-checked-icon-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "radio-checked-icon-disabled": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "radio-checked-icon-hover": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "radio-checked-icon-idle": "light-dark(rgb(255 255 255), rgb(255 255 255))"
      },
      "fontFamily": {
        "radio-global-description-text-style": "Inter, system-ui, sans-serif",
        "radio-global-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "radio-global-description-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "radio-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "radio-global-box-border-width": "1px",
        "radio-global-box-margin-x": "4px",
        "radio-global-box-size": "16px",
        "radio-global-container-gap": "8px",
        "radio-global-container-width-max": "632px",
        "radio-global-container-width-min": "16px",
        "radio-global-container-content-gap": "0px",
        "radio-global-container-content-width-max": "632px"
      },
      "borderRadius": {
        "radio-global-box-border-radius": "999px"
      }
    },
  },
};
