// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: Resizable
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "borderColor": {
        "resizable-border-active": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "resizable-border-hover": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "spacing": {
        "resizable-bar-height": "32px",
        "resizable-bar-width": "7px",
        "resizable-border-width": "1px"
      },
      "borderRadius": {
        "resizable-bar-border-radius": "4px"
      }
    },
  },
};
