// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: SearchGlobal
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "search-global-box": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "search-global-shortcut": "light-dark(rgb(54 65 74), rgb(54 65 74))"
      },
      "fill": {
        "search-global-icon": "light-dark(rgb(130 23 130), rgb(250 209 250))"
      },
      "fontFamily": {
        "search-global-placeholoder-text-style": "Inter, system-ui, sans-serif",
        "search-global-shortcut-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "search-global-placeholoder-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "search-global-shortcut-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "search-global-box-border-width": "2px",
        "search-global-box-gap": "8px",
        "search-global-box-height": "48px",
        "search-global-box-padding-x": "16px",
        "search-global-box-width": "512px",
        "search-global-box-width-max": "512px",
        "search-global-box-width-min": "256px",
        "search-global-icon-size": "16px"
      },
      "borderRadius": {
        "search-global-box-border-radius": "24px"
      }
    },
  },
};
