// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: SidebarSecondary
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "sidebar-secondary-menu-item-selected-container-active": "light-dark(rgb(216 222 228), rgb(216 222 228))",
        "sidebar-secondary-menu-item-selected-container-hover": "light-dark(rgb(216 222 228), rgb(216 222 228))",
        "sidebar-secondary-menu-item-selected-container-idle": "light-dark(rgb(216 222 228), rgb(216 222 228))",
        "sidebar-secondary-menu-item-unselected-container-active": "light-dark(rgb(236 238 239), rgb(236 238 239))",
        "sidebar-secondary-menu-item-unselected-container-hover": "light-dark(rgb(236 238 239), rgb(236 238 239))",
        "sidebar-secondary-menu-item-unselected-container-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "sidebar-secondary-global-container": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "sidebar-secondary-menu-item-global-label": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "sidebar-secondary-menu-item-extras-global-shortcut": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "sidebar-secondary-section-label-section": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "sidebar-secondary-global-header-label": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "sidebar-secondary-collapsed-breadcrumb-label": "light-dark(rgb(54 65 74), rgb(54 65 74))",
        "sidebar-secondary-collapsed-label-current-page": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "borderColor": {
        "sidebar-secondary-global-container-border-color": "light-dark(rgb(199 203 207), rgb(199 203 207))",
        "sidebar-secondary-global-container-footer-border-color": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fill": {
        "sidebar-secondary-menu-item-global-icon": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "sidebar-secondary-menu-item-extras-global-external-icon": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "sidebar-secondary-section-icon-arrow": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "sidebar-secondary-collapsed-icon-separator": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fontFamily": {
        "sidebar-secondary-menu-item-global-label-text-style": "Inter, system-ui, sans-serif",
        "sidebar-secondary-menu-item-extras-global-shortcut-text-style": "Inter, system-ui, sans-serif",
        "sidebar-secondary-section-label-section-text-style": "Inter, system-ui, sans-serif",
        "sidebar-secondary-global-header-label-text-style": "Inter, system-ui, sans-serif",
        "sidebar-secondary-collapsed-breadcrumb-label-text-style": "Inter, system-ui, sans-serif",
        "sidebar-secondary-collapsed-label-current-page-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "sidebar-secondary-menu-item-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "sidebar-secondary-menu-item-extras-global-shortcut-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "sidebar-secondary-section-label-section-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "sidebar-secondary-global-header-label-text-style": [
          "24px",
          {
            "lineHeight": "32px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "sidebar-secondary-collapsed-breadcrumb-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "sidebar-secondary-collapsed-label-current-page-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "sidebar-secondary-menu-item-global-container-gap": "8px",
        "sidebar-secondary-menu-item-global-container-height-min": "40px",
        "sidebar-secondary-menu-item-global-container-padding-x": "16px",
        "sidebar-secondary-menu-item-global-container-padding-y": "8px",
        "sidebar-secondary-menu-item-global-icon-margin-t": "4px",
        "sidebar-secondary-menu-item-global-icon-size": "16px",
        "sidebar-secondary-menu-item-extras-global-container-gap": "8px",
        "sidebar-secondary-menu-item-extras-global-external-icon-size": "16px",
        "sidebar-secondary-section-menu-item-list-gap": "0px",
        "sidebar-secondary-section-container-padding-y": "8px",
        "sidebar-secondary-section-container-header-gap": "8px",
        "sidebar-secondary-section-container-header-min-width": "undefinedundefined",
        "sidebar-secondary-section-container-header-padding-x": "16px",
        "sidebar-secondary-section-container-header-padding-y": "8px",
        "sidebar-secondary-global-container-border-width": "1px",
        "sidebar-secondary-global-container-footer-border-width": "1px",
        "sidebar-secondary-global-container-header-padding-x": "16px",
        "sidebar-secondary-global-container-header-padding-y": "12px",
        "sidebar-secondary-global-section-list-gap": "0px",
        "sidebar-secondary-collapsed-container-width": "48px",
        "sidebar-secondary-collapsed-container-content-gap": "4px",
        "sidebar-secondary-collapsed-container-content-padding-y": "16px",
        "sidebar-secondary-collapsed-container-header-padding-x": "8px",
        "sidebar-secondary-collapsed-container-header-padding-y": "16px",
        "sidebar-secondary-collapsed-icon-separator-size": "16px",
        "sidebar-secondary-expanded-container-width": "256px",
        "sidebar-secondary-expanded-container-header-padding-x": "16px",
        "sidebar-secondary-expanded-container-header-padding-y": "8px"
      }
    },
  },
};
