// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: deep-sky • component: Table
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "textColor": {
        "table-data-value-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "table-data-value-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "table-header-label": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "borderColor": {
        "table-global-cell-border-color": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fontFamily": {
        "table-data-value-text-style": "Inter, system-ui, sans-serif",
        "table-header-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "table-data-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "table-header-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "table-data-gap": "8px",
        "table-header-cell-padding-x": "16px",
        "table-header-gap": "8px",
        "table-header-sort-icon-size": "16px",
        "table-global-cell-border-width": "1px",
        "table-global-cell-min-height": "40px",
        "table-global-cell-padding-x": "16px",
        "table-global-cell-padding-y": "8px"
      }
    },
  },
};
