// Generated by @spec-lab/style-dictionary — DO NOT EDIT.
// Source: @spec-lab/design-tokens • brand: acronis • semantic tokens
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "brand-primary": "light-dark(rgb(0 32 77), rgb(12 12 14))",
        "brand-primary-active": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "brand-primary-disabled": "light-dark(rgb(117 174 240), rgb(85 89 94))",
        "brand-primary-focus": "light-dark(rgb(11 66 142), rgb(113 119 134))",
        "brand-primary-hover": "light-dark(rgb(3 43 99), rgb(61 63 67))",
        "brand-secondary": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "brand-secondary-active": "light-dark(rgb(13 77 165), rgb(101 106 122))",
        "brand-secondary-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "brand-secondary-hover": "light-dark(rgb(19 84 174), rgb(23 99 207))",
        "inverted-active": "light-dark(rgb(19 84 174), rgb(23 99 207))",
        "inverted-disabled": "light-dark(rgb(6 54 121), rgb(190 215 244))",
        "inverted-hover": "light-dark(rgb(13 77 165), rgb(101 106 122))",
        "inverted-primary": "light-dark(rgb(11 66 142), rgb(113 119 134))",
        "overlay-inverted": "light-dark(rgb(255 255 255 / 0.898), rgb(255 255 255 / 0.102))",
        "overlay-inverted-dark": "light-dark(rgb(25 27 35), rgb(255 255 255))",
        "overlay-primary": "light-dark(rgb(25 27 35 / 0.898), rgb(25 27 35 / 0.898))",
        "status-ai": "light-dark(rgb(249 245 251), rgb(62 15 62))",
        "status-ai-hover": "light-dark(rgb(245 238 248), rgb(87 15 87))",
        "status-ai-pressed": "light-dark(rgb(236 222 242), rgb(108 19 108))",
        "status-critical": "light-dark(rgb(255 240 230), rgb(77 35 0))",
        "status-critical-hover": "light-dark(rgb(255 231 214), rgb(102 45 0))",
        "status-critical-pressed": "light-dark(rgb(255 222 194), rgb(128 58 0))",
        "status-danger": "light-dark(rgb(253 237 237), rgb(87 15 15))",
        "status-danger-hover": "light-dark(rgb(252 227 227), rgb(108 19 19))",
        "status-danger-pressed": "light-dark(rgb(251 218 218), rgb(130 23 23))",
        "status-info": "light-dark(rgb(238 242 247), rgb(26 47 77))",
        "status-info-hover": "light-dark(rgb(226 235 245), rgb(32 58 95))",
        "status-info-pressed": "light-dark(rgb(214 228 245), rgb(38 70 115))",
        "status-neutral": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "status-neutral-hover": "light-dark(rgb(236 237 238), rgb(37 38 40))",
        "status-neutral-pressed": "light-dark(rgb(228 229 231), rgb(48 50 54))",
        "status-off": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "status-on": "light-dark(rgb(70 185 89), rgb(70 185 89))",
        "status-success": "light-dark(rgb(238 247 239), rgb(3 58 17))",
        "status-success-hover": "light-dark(rgb(226 245 229), rgb(8 69 23))",
        "status-success-pressed": "light-dark(rgb(209 240 214), rgb(15 87 33))",
        "status-warning": "light-dark(rgb(255 249 229), rgb(102 73 0))",
        "status-warning-hover": "light-dark(rgb(255 244 204), rgb(102 73 0))",
        "status-warning-pressed": "light-dark(rgb(255 238 178), rgb(138 99 0))",
        "status-strong-critical": "light-dark(rgb(255 128 0), rgb(255 128 0))",
        "status-strong-critical-hover": "light-dark(rgb(240 112 0), rgb(255 153 51))",
        "status-strong-critical-pressed": "light-dark(rgb(214 96 0), rgb(255 178 102))",
        "status-strong-danger": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "status-strong-danger-hover": "light-dark(rgb(195 34 34), rgb(244 154 154))",
        "status-strong-danger-pressed": "light-dark(rgb(173 31 31), rgb(248 195 195))",
        "status-strong-info": "light-dark(rgb(23 99 207), rgb(102 144 204))",
        "status-strong-info-hover": "light-dark(rgb(19 84 174), rgb(121 158 210))",
        "status-strong-info-pressed": "light-dark(rgb(13 77 165), rgb(140 176 217))",
        "status-strong-neutral": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "status-strong-neutral-hover": "light-dark(rgb(97 101 107), rgb(135 139 146))",
        "status-strong-neutral-pressed": "light-dark(rgb(85 89 94), rgb(175 178 182))",
        "status-strong-success": "light-dark(rgb(41 163 61), rgb(72 209 94))",
        "status-strong-success-hover": "light-dark(rgb(36 143 54), rgb(107 199 122))",
        "status-strong-success-pressed": "light-dark(rgb(31 122 46), rgb(126 206 139))",
        "status-strong-warning": "light-dark(rgb(245 184 0), rgb(245 184 0))",
        "status-strong-warning-hover": "light-dark(rgb(229 164 0), rgb(255 196 0))",
        "status-strong-warning-pressed": "light-dark(rgb(204 146 0), rgb(255 210 61))",
        "surface-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "surface-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "surface-primary": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "surface-secondary": "light-dark(rgb(248 250 252), rgb(24 25 27))",
        "transparent": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "on-brand-disabled": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "on-brand-link": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "on-brand-link-disabled": "light-dark(rgb(255 255 255 / 0.898), rgb(255 255 255 / 0.102))",
        "on-brand-link-hover": "light-dark(rgb(117 174 240), rgb(85 89 94))",
        "on-brand-link-pressed": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "on-brand-primary": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "on-brand-secondary": "light-dark(rgb(255 255 255 / 0.6), rgb(255 255 255 / 0.502))",
        "on-inverted-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(255 255 255 / 0.6))",
        "on-inverted-primary": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "on-overlay-inverted-light": "light-dark(rgb(255 255 255), rgb(24 25 27))",
        "on-overlay-link": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "on-overlay-link-hover": "light-dark(rgb(117 174 240), rgb(85 89 94))",
        "on-overlay-link-pressed": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "on-overlay-primary": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "on-overlay-secondary": "light-dark(rgb(255 255 255 / 0.6), rgb(255 255 255 / 0.502))",
        "on-status-ai": "light-dark(rgb(130 23 130), rgb(250 209 250))",
        "on-status-critical": "light-dark(rgb(153 69 0), rgb(255 222 194))",
        "on-status-danger": "light-dark(rgb(152 27 27), rgb(251 218 218))",
        "on-status-info": "light-dark(rgb(6 54 121), rgb(214 228 245))",
        "on-status-link": "light-dark(rgb(6 54 121), rgb(214 228 245))",
        "on-status-link-disabled": "light-dark(rgb(117 174 240), rgb(48 89 145))",
        "on-status-link-hover": "light-dark(rgb(0 32 77), rgb(238 242 247))",
        "on-status-link-pressed": "light-dark(rgb(0 21 51), rgb(248 250 252))",
        "on-status-neutral": "light-dark(rgb(61 63 67), rgb(215 217 219))",
        "on-status-primary": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "on-status-secondary": "light-dark(rgb(61 63 67), rgb(215 217 219))",
        "on-status-success": "light-dark(rgb(15 87 33), rgb(209 240 214))",
        "on-status-warning": "light-dark(rgb(138 99 0), rgb(255 238 178))",
        "on-surface-destructive": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "on-surface-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "on-surface-link": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "on-surface-link-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "on-surface-link-hover": "light-dark(rgb(19 84 174), rgb(23 99 207))",
        "on-surface-link-pressed": "light-dark(rgb(6 54 121), rgb(190 215 244))",
        "on-surface-primary": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "on-surface-secondary": "light-dark(rgb(109 114 120), rgb(109 114 120))"
      },
      "borderColor": {
        "border-on-brand": "light-dark(rgb(255 255 255 / 0.102), rgb(255 255 255 / 0.102))",
        "on-brand-border-active": "light-dark(rgb(244 245 245), rgb(24 25 27))",
        "on-brand-divider": "light-dark(rgb(255 255 255 / 0.102), rgb(255 255 255 / 0.102))",
        "on-status-critical": "light-dark(rgb(255 204 153), rgb(153 69 0))",
        "on-status-critical-strong": "light-dark(rgb(240 112 0), rgb(255 153 51))",
        "on-status-danger": "light-dark(rgb(248 195 195), rgb(151 27 27))",
        "on-status-danger-strong": "light-dark(rgb(217 38 38), rgb(237 94 94))",
        "on-status-info": "light-dark(rgb(190 215 244), rgb(45 82 133))",
        "on-status-info-strong": "light-dark(rgb(19 84 174), rgb(121 158 210))",
        "on-status-neutral": "light-dark(rgb(201 204 207), rgb(73 76 80))",
        "on-status-neutral-strong": "light-dark(rgb(97 101 107), rgb(135 139 146))",
        "on-status-success": "light-dark(rgb(178 229 187), rgb(26 102 38))",
        "on-status-success-strong": "light-dark(rgb(36 143 54), rgb(107 199 122))",
        "on-status-warning": "light-dark(rgb(255 227 128), rgb(178 128 0))",
        "on-status-warning-strong": "light-dark(rgb(229 164 0), rgb(255 196 0))",
        "border-on-surface": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "on-surface-border-active": "light-dark(rgb(23 99 207), rgb(71 152 245))",
        "on-surface-border-error": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "on-surface-divider": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "transparent": "light-dark(transparent, transparent)"
      },
      "fill": {
        "on-brand-disabled": "light-dark(rgb(255 255 255 / 0.102), rgb(255 255 255 / 0.102))",
        "on-brand-primary": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "on-brand-secondary": "light-dark(rgb(255 255 255 / 0.6), rgb(255 255 255 / 0.502))",
        "on-inverted-disabled": "light-dark(rgb(255 255 255 / 0.302), rgb(255 255 255 / 0.6))",
        "on-inverted-primary": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "on-inverted-secondary": "light-dark(rgb(255 255 255 / 0.6), rgb(255 255 255 / 0.502))",
        "on-overlay-primary": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "on-status-ai": "light-dark(rgb(130 23 130), rgb(250 209 250))",
        "on-status-critical": "light-dark(rgb(153 69 0), rgb(255 222 194))",
        "on-status-danger": "light-dark(rgb(152 27 27), rgb(251 218 218))",
        "on-status-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "on-status-info": "light-dark(rgb(6 54 121), rgb(214 228 245))",
        "on-status-neutral": "light-dark(rgb(61 63 67), rgb(215 217 219))",
        "on-status-primary": "light-dark(rgb(6 54 121), rgb(214 228 245))",
        "on-status-success": "light-dark(rgb(15 87 33), rgb(209 240 214))",
        "on-status-warning": "light-dark(rgb(138 99 0), rgb(255 238 178))",
        "on-surface-brand": "light-dark(rgb(0 32 77), rgb(12 12 14))",
        "on-surface-destructive": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "on-surface-disabled": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "on-surface-neutral": "light-dark(rgb(201 204 207), rgb(73 76 80))",
        "on-surface-primary": "light-dark(rgb(23 99 207), rgb(71 152 245))"
      },
      "ringColor": {
        "brand": "light-dark(rgb(190 215 244), rgb(11 66 142))",
        "error": "light-dark(rgb(248 195 195), rgb(151 27 27))",
        "primary": "light-dark(rgb(190 215 244), rgb(11 66 142))",
        "secondary": "light-dark(rgb(190 215 244), rgb(11 66 142))"
      },
      "backgroundImage": {
        "on-status-ai-strong": "linear-gradient(90deg, rgb(56 73 224) 20%, rgb(252 45 241) 100%)",
        "ai-active": "linear-gradient(90deg, rgb(43 54 155) 20%, rgb(118 21 113) 100%)",
        "ai-disabled": "linear-gradient(90deg, rgb(223 226 255) 20%, rgb(255 218 253) 100%)",
        "ai-hover": "linear-gradient(90deg, rgb(51 66 195) 20%, rgb(182 33 174) 100%)",
        "ai-idle": "linear-gradient(90deg, rgb(56 73 224) 20%, rgb(252 45 241) 100%)"
      },
      "fontFamily": {
        "typography-body-accent": "Inter, system-ui, sans-serif",
        "typography-body-default": "Inter, system-ui, sans-serif",
        "typography-body-form-label": "Inter, system-ui, sans-serif",
        "typography-body-heading": "Inter, system-ui, sans-serif",
        "typography-body-strong": "Inter, system-ui, sans-serif",
        "typography-caption-accent": "Inter, system-ui, sans-serif",
        "typography-caption-default": "Inter, system-ui, sans-serif",
        "typography-caption-strong": "Inter, system-ui, sans-serif",
        "typography-fineprint-heading": "Inter, system-ui, sans-serif",
        "typography-headings-display": "Inter, system-ui, sans-serif",
        "typography-headings-lead": "Inter, system-ui, sans-serif",
        "typography-headings-title": "Inter, system-ui, sans-serif",
        "typography-headings-title-accent": "Inter, system-ui, sans-serif",
        "typography-link-default": "Inter, system-ui, sans-serif",
        "typography-link-default-underline": "Inter, system-ui, sans-serif",
        "typography-link-strong": "Inter, system-ui, sans-serif",
        "typography-link-strong-underline": "Inter, system-ui, sans-serif",
        "typography-note-default": "Inter, system-ui, sans-serif",
        "typography-note-heading": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "typography-body-accent": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ],
        "typography-body-default": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "typography-body-form-label": [
          "14px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "typography-body-heading": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0.3px",
            "fontWeight": "600"
          }
        ],
        "typography-body-strong": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "typography-caption-accent": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ],
        "typography-caption-default": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "typography-caption-strong": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "typography-fineprint-heading": [
          "10px",
          {
            "lineHeight": "16px",
            "letterSpacing": "1px",
            "fontWeight": "700"
          }
        ],
        "typography-headings-display": [
          "32px",
          {
            "lineHeight": "40px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "typography-headings-lead": [
          "18px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "typography-headings-title": [
          "24px",
          {
            "lineHeight": "32px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "typography-headings-title-accent": [
          "24px",
          {
            "lineHeight": "32px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "typography-link-default": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "typography-link-default-underline": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "typography-link-strong": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "typography-link-strong-underline": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ],
        "typography-note-default": [
          "11px",
          {
            "lineHeight": "16px",
            "letterSpacing": "1px",
            "fontWeight": "600"
          }
        ],
        "typography-note-heading": [
          "11px",
          {
            "lineHeight": "16px",
            "letterSpacing": "1px",
            "fontWeight": "700"
          }
        ]
      }
    },
  },
};
