name: Utils - Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/utils/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog:
    if: github.repository == 'acronis/ui-component-library'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.3.0
        with:
          preset: "conventionalcommits"
          github-token: ${{ secrets.ACV_TOKEN }}
          version-file: './packages/utils/package.json'
          output-file: './packages/utils/CHANGELOG.md'
          tag-prefix: 'utils/'
          git-path: './packages/utils'
